---
- name: Bootstrap the k3s cluster
  hosts: pi
  become: true
  roles:
    - os-prerequisites
    - ssh_hardening
    - fail2ban
    - k3s
    - cilium
    - cnpg
    - argocd
    - sealed-secrets
    - argocd-image-updater
    - bootstrap-app
