minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080

blockExoticSubdeps: true

allowBuilds:
  '@ast-grep/cli': true
  '@parcel/watcher': true
  '@swc/core': true
  better-sqlite3: true
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true

