export type ToolWorkbenchProps = { slug: string };

export const textTools = new Set([
  'text-counter',
  'text-reverser',
  'line-break-remover',
  'whitespace-trimmer',
  'duplicate-line-remover',
  'accent-remover',
  'slugify',
  'text-repeater',
  'text-case',
  'case-style-converter',
  'dot-case-converter',
  'duplicate-word-finder',
  'palindrome-checker',
  'word-frequency-counter',
  'line-sorter',
  'reading-time-estimator',
  'invisible-char-remover',
  'pig-latin',
  'leetspeak',
  'uwu-speak',
  'lorem-ipsum-generator',
  'nato-phonetic-alphabet',
  'roman-numeral-converter',
  'morse-code-translator',
  'vigenere-cipher',
]);

export const multilineTools = new Set([
  ...textTools,
  'json-formatter',
  'json-to-csv',
  'markdown-to-html',
  'markdown-table-generator',
  'env-file-validator',
  'find-and-replace',
  'regex-tester',
  'robots-txt-generator',
  'gitignore-generator',
  'jwt-decoder',
  'query-string-parser',
  'base64-encoder',
  'binary-text-codec',
  'hex-text-codec',
  'html-entity-codec',
  'url-encoder',
  'utf8-inspector',
  'cipher-tool',
  'number-base-converter',
]);

export const calculationTools = new Set([
  'quadratic-equation',
  'percentage-calculator',
  'gcd-lcm-calculator',
  'prime-factorization',
  'combinatorics',
  'sequences',
  'base-converter',
  'fractions',
  'fraction-calculator',
  'linear-systems',
  'linear-system-2x2',
  'linear-system-3x3',
  'matrix-calculator',
  'vector-calculator',
  'correlation-calculator',
  'linear-regression',
  'normal-distribution',
  'age-calculator',
  'date-difference-calculator',
  'bmi-calculator',
  'complex-number-calculator',
  'triangle-calculator',
  'unit-converter',
  'arithmetic-progression',
  'geometric-progression',
  'function-plotter',
  'statistics-analyzer',
  'statistics',
  'number-theory',
  'compound-interest',
  'ohm-law',
]);

export const imageTools = new Set([
  'image-color-picker',
  'image-compressor',
  'image-dimension-calculator',
  'image-format-converter',
  'image-resizer',
  'image-to-base64',
  'svg-to-png',
]);

export const defaultInput: Record<string, string> = {
  'text-counter': 'Olá, mundo! Este texto pode ser analisado.',
  'text-reverser': 'Olá, mundo!',
  'line-break-remover': 'uma linha\noutra linha',
  'whitespace-trimmer': '  texto   com   espaços  ',
  'duplicate-line-remover': 'alpha\nbeta\nalpha',
  'accent-remover': 'ação, informação e café',
  slugify: 'Uma página sobre software',
  'text-repeater': 'linha',
  'text-case': 'Olá, mundo!',
  'case-style-converter': 'uma frase de exemplo',
  'dot-case-converter': 'Uma frase de exemplo',
  'duplicate-word-finder': 'casa carro casa livro carro casa',
  'palindrome-checker': 'A base do teto desaba',
  'word-frequency-counter': 'casa carro casa livro carro casa',
  'line-sorter': 'zeta\nalfa\nbeta',
  'reading-time-estimator': 'Este texto estima o tempo de leitura.',
  'invisible-char-remover': 'texto\u200Bsem caractere invisível',
  'lorem-ipsum-generator': '3',
  'pig-latin': 'hello world',
  leetspeak: 'Hello world',
  'uwu-speak': 'really lovely words',
  'json-formatter': '{"name":"portfolio","active":true}',
  'json-to-csv': '[{"name":"Gabriel","role":"developer"}]',
  'base-converter': '255',
  'number-base-converter': '255',
  'quadratic-equation': '1,-3,2',
  'percentage-calculator': '200,15',
  'gcd-lcm-calculator': '24,36',
  'prime-factorization': '360',
  combinatorics: '5,2',
  'fraction-calculator': '1/2 + 1/3',
  'linear-system-2x2': '2,1,5,1,-1,1',
  'linear-system-3x3': '1,1,1,6,2,-1,1,3,1,2,1,4',
  'linear-systems': '2,1,5,1,-1,1',
  statistics: '12,18,21,24,30',
  'statistics-analyzer': '12,18,21,24,30',
  'number-theory': '360',
  sequences: '2,3,5',
  fractions: '1/2 + 1/3',
  'matrix-calculator': '1,2,3,4',
  'vector-calculator': '1,2,3;4,5,6',
  'correlation-calculator': '1,2,3,4;2,4,5,8',
  'linear-regression': '1,2,3,4;2,4,5,8',
  'normal-distribution': '0,1,1.96',
  'complex-number-calculator': '1,2,3,4',
  'bmi-calculator': '80,1.8',
  'triangle-calculator': '3,4,5',
  'unit-converter': '100',
  kinematics: '10,2,5',
  'newtons-second-law': '10,2',
  'ideal-gas': '1,300,24',
  'wave-calculator': '2,3',
  'projectile-motion': '20,45',
  'circular-motion': '10,5',
  'mechanical-energy': '10,4,3',
  'sensible-heat': '2,4,10',
  'dilution-calculator': '1,2,4',
  'ph-calculator': '0.01',
  'moles-calculator': '18,18',
  'roi-calculator': '100,140',
  'inflation-calculator': '100,5,3',
  'break-even-calculator': '1000,50,20',
  'compound-interest-calculator': '1000,5,10',
  'compound-interest': '1000,5,10',
  'amortization-calculator': '10000,6,24',
  'loan-interest-calculator': '10000,6,24',
  'resistor-network': '10,20,30',
  'composition-calculator': '25,100',
  'ohms-law': '12,2',
  'ohm-law': '12,2',
  'age-calculator': '2000-01-01',
  'date-difference-calculator': '2020-01-01',
  'random-number-generator': '1',
  'random-date-generator': '2025-01-01',
  'fake-name-generator': '1',
  'uuid-generator': 'generate',
  'timestamp-converter': '2025-01-01',
  'periodic-table': 'Fe',
  'color-converter': '#336699',
  'contrast-checker': '#ffffff,#111111',
  'css-border-radius-generator': '1rem',
  'css-box-shadow-generator': '0 0.5rem 1rem rgba(0,0,0,.2)',
  'css-clamp-calculator': '1rem',
  'css-gradient-generator': '#111,#777',
  'http-status-reference': '200',
  'robots-txt-generator': '/admin',
  'gitignore-generator': '.DS_Store',
  'query-string-parser': '?page=2&sort=desc',
  'utf8-inspector': 'Olá',
  'user-agent-parser': 'browser',
  'viewport-info': 'browser',
  'cipher-tool': 'hello world',
  'vigenere-cipher': 'hello world',
};

export const defaultSecond: Record<string, string> = {
  'text-repeater': '3',
  'find-and-replace': 'foo',
  'regex-tester': '\\d+',
  'vigenere-cipher': 'key',
  'random-number-generator': '100',
  'date-difference-calculator': '2025-01-01',
};

export const defaultThird: Record<string, string> = {
  'find-and-replace': 'bar',
  'date-difference-calculator': '',
};

export const numericFieldLabels: Record<string, string[]> = {
  'quadratic-equation': ['a', 'b', 'c'],
  'percentage-calculator': ['value', 'percentage'],
  'gcd-lcm-calculator': ['first value', 'second value'],
  'prime-factorization': ['value'],
  combinatorics: ['n', 'r'],
  'base-converter': ['value', 'source base', 'target base'],
  'fraction-calculator': ['expression'],
  'bmi-calculator': ['weight', 'height'],
  'triangle-calculator': ['side a', 'side b', 'side c'],
  'arithmetic-progression': ['first term', 'difference', 'position'],
  'geometric-progression': ['first term', 'ratio', 'position'],
  'normal-distribution': ['mean', 'deviation', 'value'],
  statistics: ['values'],
  'statistics-analyzer': ['values'],
  'number-theory': ['value'],
  sequences: ['first term', 'difference', 'count'],
  kinematics: ['initial velocity', 'acceleration', 'time'],
  'newtons-second-law': ['mass', 'acceleration'],
  'ideal-gas': ['moles', 'temperature', 'volume'],
  'wave-calculator': ['frequency', 'wavelength'],
  'projectile-motion': ['velocity', 'angle'],
  'circular-motion': ['velocity', 'radius'],
  'mechanical-energy': ['mass', 'velocity', 'height'],
  'sensible-heat': ['mass', 'specific heat', 'temperature'],
  'dilution-calculator': ['initial concentration', 'initial volume', 'final volume'],
  'ph-calculator': ['hydrogen concentration'],
  'moles-calculator': ['mass', 'molar mass'],
  'roi-calculator': ['investment', 'return'],
  'inflation-calculator': ['value', 'rate', 'years'],
  'break-even-calculator': ['fixed costs', 'unit price', 'unit cost'],
  'compound-interest-calculator': ['principal', 'rate', 'years'],
  'compound-interest': ['principal', 'rate', 'years'],
  'amortization-calculator': ['principal', 'annual rate', 'payments'],
  'loan-interest-calculator': ['principal', 'annual rate', 'payments'],
  'resistor-network': ['resistor 1', 'resistor 2', 'resistor 3'],
  'composition-calculator': ['part', 'whole'],
  'ohms-law': ['voltage', 'resistance'],
  'ohm-law': ['voltage', 'resistance'],
  'complex-number-calculator': ['real a', 'imaginary a', 'real b', 'imaginary b'],
  'linear-system-2x2': ['a', 'b', 'c', 'd', 'e', 'f'],
  'linear-system-3x3': ['a₁', 'b₁', 'c₁', 'd₁', 'a₂', 'b₂', 'c₂', 'd₂', 'a₃', 'b₃', 'c₃', 'd₃'],
};

export const noPrimaryInputTools = new Set([
  'color-wheel',
  'fake-name-generator',
  'random-color-palette',
  'random-date-generator',
  'uuid-generator',
  'user-agent-parser',
  'viewport-info',
]);
