using System.Data.Common;

namespace Portfolio.Blazor.Data.Tests;

internal static class Seed
{
    private const string Ts = "'2026-08-01 10:00:00'";

    internal static readonly string[] Statements =
    [
        $"insert into site_settings (id, short_name, portfolio_url, maintenance_enabled, contact_email, contact_available, source_repository_url, created_at, updated_at) values (1, 'GA', 'https://example.test', false, 'hello@example.test', true, 'https://github.com/example/portfolio', {Ts}, {Ts})",
        $"insert into site_settings_translations (id, site_settings_id, locale, copyright_template, maintenance_eyebrow, maintenance_title, maintenance_description, seo, created_at, updated_at) values (1, 1, 'en', 'copyright {{year}}', 'maintenance', 'back soon', 'we are working on it', '{{\"title\":\"site\"}}', {Ts}, {Ts})",
        $"insert into site_settings_translations (id, site_settings_id, locale, copyright_template, maintenance_eyebrow, maintenance_title, maintenance_description, seo, created_at, updated_at) values (2, 1, 'pt-BR', 'direitos {{year}}', 'manutencao', 'voltamos logo', 'estamos trabalhando', '{{\"title\":\"site pt\"}}', {Ts}, {Ts})",
        $"insert into contact_profiles (id, site_settings_id, platform, label, url, \"order\", created_at, updated_at) values (1, 1, 'github', 'github', 'https://github.com/example', 1, {Ts}, {Ts})",
        $"insert into contact_profiles (id, site_settings_id, platform, label, url, \"order\", created_at, updated_at) values (2, 1, 'linkedin', 'linkedin', 'https://linkedin.com/in/example', 2, {Ts}, {Ts})",
        $"insert into profiles (id, name, birth_date, created_at, updated_at) values (1, 'Example Person', '1990-05-20', {Ts}, {Ts})",
        $"insert into profile_translations (id, profile_id, locale, title, location, birth_city, description, interests, learning, personal_interests, trajectory, milestones, created_at, updated_at, fortunes, personal_facts, personal_things) values (1, 1, 'en', 'engineer', 'Somewhere', 'Town', 'builds things', 'systems', 'rust', '[\"music\"]', 'a path', '[{{\"year\":\"2020\",\"text\":\"started\"}}]', {Ts}, {Ts}, '[\"fortune\"]', '[\"fact\"]', '[\"thing\"]')",
        $"insert into profile_translations (id, profile_id, locale, title, location, birth_city, description, interests, learning, personal_interests, trajectory, milestones, created_at, updated_at, fortunes, personal_facts, personal_things) values (2, 1, 'pt-BR', 'engenheiro', 'Em algum lugar', 'Cidade', 'constroi coisas', 'sistemas', 'rust', '[\"musica\"]', 'um caminho', '[{{\"year\":\"2020\",\"text\":\"comecou\"}}]', {Ts}, {Ts}, '[\"sorte\"]', '[\"fato\"]', '[\"coisa\"]')",
        $"insert into pages (id, slug, created_at, updated_at) values (1, 'home', {Ts}, {Ts})",
        $"insert into pages (id, slug, created_at, updated_at) values (2, 'portfolio', {Ts}, {Ts})",
        $"insert into pages (id, slug, created_at, updated_at) values (3, 'projects', {Ts}, {Ts})",
        $"insert into page_translations (id, page_id, locale, fields, created_at, updated_at) values (1, 1, 'en', '{{\"title\":\"home\",\"heroIdentity\":\"hi\"}}', {Ts}, {Ts})",
        $"insert into page_translations (id, page_id, locale, fields, created_at, updated_at) values (2, 1, 'pt-BR', '{{\"title\":\"inicio\",\"heroIdentity\":\"oi\"}}', {Ts}, {Ts})",
        $"insert into page_translations (id, page_id, locale, fields, created_at, updated_at) values (3, 2, 'en', '{{\"title\":\"portfolio\"}}', {Ts}, {Ts})",
        $"insert into page_translations (id, page_id, locale, fields, created_at, updated_at) values (4, 3, 'en', '{{\"title\":\"projects\",\"selectedLabel\":\"selected\"}}', {Ts}, {Ts})",
        $"insert into technologies (id, slug, \"order\", code, logo, created_at, updated_at, public_id) values (1, 'dotnet', 1, 'cs', null, {Ts}, {Ts}, 'a1b2c3')",
        $"insert into technologies (id, slug, \"order\", code, logo, created_at, updated_at, public_id) values (2, 'postgres', 2, 'sql', null, {Ts}, {Ts}, 'a1b2c4')",
        $"insert into technology_translations (id, technology_id, locale, name, created_at, updated_at) values (1, 1, 'en', '.NET', {Ts}, {Ts})",
        $"insert into technology_translations (id, technology_id, locale, name, created_at, updated_at) values (2, 2, 'en', 'PostgreSQL', {Ts}, {Ts})",
        $"insert into topics (id, slug, \"order\", kind, parent_id, created_at, updated_at, public_id) values (1, 'systems', 1, 'topic', null, {Ts}, {Ts}, 'b1b2c3')",
        $"insert into topics (id, slug, \"order\", kind, parent_id, created_at, updated_at, public_id) values (2, 'databases', 2, 'topic', 1, {Ts}, {Ts}, 'b1b2c4')",
        $"insert into topics (id, slug, \"order\", kind, parent_id, created_at, updated_at, public_id) values (3, 'author-x', 3, 'person', null, {Ts}, {Ts}, 'b1b2c5')",
        $"insert into topic_translations (id, topic_id, locale, name, created_at, updated_at) values (1, 1, 'en', 'Systems', {Ts}, {Ts})",
        $"insert into topic_translations (id, topic_id, locale, name, created_at, updated_at) values (2, 1, 'pt-BR', 'Sistemas', {Ts}, {Ts})",
        $"insert into topic_translations (id, topic_id, locale, name, created_at, updated_at) values (3, 2, 'en', 'Databases', {Ts}, {Ts})",
        $"insert into topic_translations (id, topic_id, locale, name, created_at, updated_at) values (4, 3, 'en', 'Author X', {Ts}, {Ts})",
        $"insert into projects (id, slug, hidden, \"order\", href, external, created_at, updated_at, nda, published_at, show_history, public_id) values (1, 'public-project', false, 1, null, false, {Ts}, {Ts}, false, '2026-03-01', true, 'c1b2c3')",
        $"insert into projects (id, slug, hidden, \"order\", href, external, created_at, updated_at, nda, published_at, show_history, public_id) values (2, 'hidden-project', true, 2, null, false, {Ts}, {Ts}, false, '2026-04-01', false, 'c1b2c4')",
        $"insert into projects (id, slug, hidden, \"order\", href, external, created_at, updated_at, nda, published_at, show_history, public_id) values (3, 'nda-project', false, 3, null, false, {Ts}, {Ts}, true, '2026-05-01', false, 'c1b2c5')",
        $"insert into projects (id, slug, hidden, \"order\", href, external, created_at, updated_at, nda, published_at, show_history, public_id) values (4, 'undated-project', false, 4, 'https://example.test/x', true, {Ts}, {Ts}, false, null, false, 'c1b2c6')",
        $"insert into project_translations (id, project_id, locale, name, purpose, problem, current_focus, status, metrics, body, seo, created_at, updated_at) values (1, 1, 'en', 'Public Project', 'to test', 'a problem', 'focus', 'active', '[{{\"label\":\"users\",\"value\":\"10\"}}]', 'body **md**', null, {Ts}, {Ts})",
        $"insert into project_translations (id, project_id, locale, name, purpose, problem, current_focus, status, metrics, body, seo, created_at, updated_at) values (2, 1, 'pt-BR', 'Projeto Publico', 'para testar', 'um problema', 'foco', 'ativo', null, 'corpo', null, {Ts}, {Ts})",
        $"insert into project_translations (id, project_id, locale, name, purpose, problem, current_focus, status, metrics, body, seo, created_at, updated_at) values (3, 2, 'en', 'Hidden Project', 'hidden', null, null, 'active', null, null, null, {Ts}, {Ts})",
        $"insert into project_translations (id, project_id, locale, name, purpose, problem, current_focus, status, metrics, body, seo, created_at, updated_at) values (4, 3, 'en', 'NDA Project', 'secret', null, null, 'active', null, null, null, {Ts}, {Ts})",
        $"insert into project_translations (id, project_id, locale, name, purpose, problem, current_focus, status, metrics, body, seo, created_at, updated_at) values (5, 4, 'en', 'Undated Project', 'no date', null, null, 'archived', null, null, null, {Ts}, {Ts})",
        "insert into project_technology (project_id, technology_id, \"order\") values (1, 1, 0)",
        "insert into project_technology (project_id, technology_id, \"order\") values (1, 2, 1)",
        "insert into project_technology (project_id, technology_id, \"order\") values (2, 1, 0)",
        $"insert into case_studies (id, slug, hidden, \"order\", href, external, visual, created_at, updated_at, nda, published_at, show_history, public_id) values (1, 'public-case', false, 1, null, false, null, {Ts}, {Ts}, false, '2026-02-01', false, 'd1b2c3')",
        $"insert into case_studies (id, slug, hidden, \"order\", href, external, visual, created_at, updated_at, nda, published_at, show_history, public_id) values (2, 'nda-case', false, 2, null, false, null, {Ts}, {Ts}, true, '2026-02-02', false, 'd1b2c4')",
        $"insert into case_study_translations (id, case_study_id, locale, title, status, meta, summary, context, role, result, metrics, body, seo, created_at, updated_at) values (1, 1, 'en', 'Public Case', 'done', 'meta', 'summary', 'context', 'lead', 'result', null, 'body', null, {Ts}, {Ts})",
        $"insert into case_study_translations (id, case_study_id, locale, title, status, meta, summary, context, role, result, metrics, body, seo, created_at, updated_at) values (2, 2, 'en', 'NDA Case', 'done', null, null, null, null, null, null, null, null, {Ts}, {Ts})",
        "insert into case_study_technology (case_study_id, technology_id, \"order\") values (1, 1, 0)",
        $"insert into writings (id, slug, hidden, date_iso, created_at, updated_at, show_history, type, public_id) values (1, 'dated-post', false, '2026-08-15', {Ts}, {Ts}, false, 'post', 'e1b2c3')",
        $"insert into writings (id, slug, hidden, date_iso, created_at, updated_at, show_history, type, public_id) values (2, 'undated-post', false, null, {Ts}, {Ts}, false, 'post', 'e1b2c4')",
        $"insert into writings (id, slug, hidden, date_iso, created_at, updated_at, show_history, type, public_id) values (3, 'hidden-post', true, '2026-08-20', {Ts}, {Ts}, false, 'post', 'e1b2c5')",
        $"insert into writings (id, slug, hidden, date_iso, created_at, updated_at, show_history, type, public_id) values (4, 'older-post', false, '2026-05-10', {Ts}, {Ts}, false, 'post', 'e1b2c6')",
        $"insert into writing_translations (id, writing_id, locale, title, excerpt, reading_time, body, seo, created_at, updated_at) values (1, 1, 'en', 'Dated Post', 'excerpt', '5 min', 'body text', null, {Ts}, {Ts})",
        $"insert into writing_translations (id, writing_id, locale, title, excerpt, reading_time, body, seo, created_at, updated_at) values (2, 1, 'pt-BR', 'Post Datado', 'resumo', '5 min', 'texto', null, {Ts}, {Ts})",
        $"insert into writing_translations (id, writing_id, locale, title, excerpt, reading_time, body, seo, created_at, updated_at) values (3, 2, 'en', 'Undated Post', null, null, 'body', null, {Ts}, {Ts})",
        $"insert into writing_translations (id, writing_id, locale, title, excerpt, reading_time, body, seo, created_at, updated_at) values (4, 3, 'en', 'Hidden Post', null, null, 'body', null, {Ts}, {Ts})",
        $"insert into writing_translations (id, writing_id, locale, title, excerpt, reading_time, body, seo, created_at, updated_at) values (5, 4, 'en', 'Older Post', null, null, 'body', null, {Ts}, {Ts})",
        "insert into topicables (id, topic_id, topicable_type, topicable_id, role) values (1, 1, 'writing', 1, null)",
        "insert into topicables (id, topic_id, topicable_type, topicable_id, role) values (2, 2, 'writing', 1, null)",
        "insert into topicables (id, topic_id, topicable_type, topicable_id, role) values (3, 1, 'writing', 4, null)",
        "insert into topicables (id, topic_id, topicable_type, topicable_id, role) values (4, 2, 'resource', 1, null)",
        "insert into topicables (id, topic_id, topicable_type, topicable_id, role) values (5, 1, 'finding', 1, null)",
        "insert into page_featured_project (page_id, project_id, \"order\") values (1, 1, 1)",
        "insert into page_featured_project (page_id, project_id, \"order\") values (1, 2, 2)",
        "insert into page_featured_case (page_id, case_study_id, \"order\") values (1, 1, 1)",
        "insert into page_featured_writing (page_id, writing_id, \"order\") values (1, 1, 1)",
        $"insert into languages (id, slug, \"order\", code, created_at, updated_at) values (1, 'english', 1, 'en', {Ts}, {Ts})",
        $"insert into language_translations (id, language_id, locale, name, created_at, updated_at) values (1, 1, 'en', 'English', {Ts}, {Ts})",
        $"insert into language_translations (id, language_id, locale, name, created_at, updated_at) values (2, 1, 'pt-BR', 'Ingles', {Ts}, {Ts})",
        $"insert into resources (id, slug, hidden, \"order\", type, language_id, authors, organizations, published_date_iso, found_date_iso, consumption_state, rating, editorial_state, visibility, type_details, created_at, updated_at, public_id) values (1, 'public-book', false, 1, 'book', 1, 'Author X', null, '2017-03-01', '2024-01-10', 'completed', 'recommended', 'published', 'public', '{{\"isbn\":\"978-0000000000\",\"pages\":\"300\"}}', {Ts}, {Ts}, 'f1b2c3')",
        $"insert into resources (id, slug, hidden, \"order\", type, language_id, authors, organizations, published_date_iso, found_date_iso, consumption_state, rating, editorial_state, visibility, type_details, created_at, updated_at, public_id) values (2, 'hidden-book', true, 2, 'book', null, null, null, '2018-01-01', null, null, null, 'published', 'public', null, {Ts}, {Ts}, 'f1b2c4')",
        $"insert into resources (id, slug, hidden, \"order\", type, language_id, authors, organizations, published_date_iso, found_date_iso, consumption_state, rating, editorial_state, visibility, type_details, created_at, updated_at, public_id) values (3, 'draft-book', false, 3, 'article', null, null, null, null, null, null, null, 'draft', 'draft', null, {Ts}, {Ts}, 'f1b2c5')",
        $"insert into resources (id, slug, hidden, \"order\", type, language_id, authors, organizations, published_date_iso, found_date_iso, consumption_state, rating, editorial_state, visibility, type_details, created_at, updated_at, public_id) values (4, 'second-book', false, 4, 'book', 1, 'Author Y', 'Org', '2020-06-15', '2025-02-02', 'exploring', 'interesting', 'published', 'public', null, {Ts}, {Ts}, 'f1b2c6')",
        $"insert into resource_translations (id, resource_id, locale, title, alternative_title, description, personal_note, reason_found, seo, created_at, updated_at) values (1, 1, 'en', 'Public Book', null, 'a book', 'liked it', 'cited often', null, {Ts}, {Ts})",
        $"insert into resource_translations (id, resource_id, locale, title, alternative_title, description, personal_note, reason_found, seo, created_at, updated_at) values (2, 1, 'pt-BR', 'Livro Publico', null, 'um livro', 'gostei', 'citado', null, {Ts}, {Ts})",
        $"insert into resource_translations (id, resource_id, locale, title, alternative_title, description, personal_note, reason_found, seo, created_at, updated_at) values (3, 2, 'en', 'Hidden Book', null, null, null, null, null, {Ts}, {Ts})",
        $"insert into resource_translations (id, resource_id, locale, title, alternative_title, description, personal_note, reason_found, seo, created_at, updated_at) values (4, 3, 'en', 'Draft Article', null, null, null, null, null, {Ts}, {Ts})",
        $"insert into resource_translations (id, resource_id, locale, title, alternative_title, description, personal_note, reason_found, seo, created_at, updated_at) values (5, 4, 'en', 'Second Book', null, 'another', null, null, null, {Ts}, {Ts})",
        $"insert into resource_links (id, resource_id, url, label, platform, purpose, is_primary, is_free, language_id, created_at, updated_at) values (1, 1, 'https://example.test/book', 'official site', 'site', 'official-source', true, false, 1, {Ts}, {Ts})",
        $"insert into resource_links (id, resource_id, url, label, platform, purpose, is_primary, is_free, language_id, created_at, updated_at) values (2, 1, 'https://github.com/example/repo', null, 'github', 'repository', false, true, null, {Ts}, {Ts})",
        $"insert into resource_identifiers (id, resource_id, kind, value, created_at, updated_at) values (1, 1, 'isbn', '978-0000000000', {Ts}, {Ts})",
        $"insert into reference_collections (id, slug, hidden, \"order\", image, created_at, updated_at, published_at, public_id) values (1, 'starter-kit', false, 1, null, {Ts}, {Ts}, '2026-01-05', '01b2c3')",
        $"insert into reference_collections (id, slug, hidden, \"order\", image, created_at, updated_at, published_at, public_id) values (2, 'hidden-kit', true, 2, null, {Ts}, {Ts}, '2026-01-06', '01b2c4')",
        $"insert into reference_collection_translations (id, reference_collection_id, locale, title, description, intro, seo, created_at, updated_at) values (1, 1, 'en', 'Starter Kit', 'desc', 'intro **md**', null, {Ts}, {Ts})",
        $"insert into reference_collection_translations (id, reference_collection_id, locale, title, description, intro, seo, created_at, updated_at) values (2, 2, 'en', 'Hidden Kit', null, null, null, {Ts}, {Ts})",
        "insert into reference_collection_item (reference_collection_id, resource_id, note, \"order\") values (1, 1, 'start here', 0)",
        "insert into reference_collection_item (reference_collection_id, resource_id, note, \"order\") values (1, 2, 'hidden item', 1)",
        "insert into reference_collection_item (reference_collection_id, resource_id, note, \"order\") values (1, 4, null, 2)",
        $"insert into experiments (id, slug, hidden, \"order\", href, external, created_at, updated_at, published_at, show_history, public_id) values (1, 'public-experiment', false, 1, null, false, {Ts}, {Ts}, '2026-07-01', false, '11b2c3')",
        $"insert into experiments (id, slug, hidden, \"order\", href, external, created_at, updated_at, published_at, show_history, public_id) values (2, 'hidden-experiment', true, 2, null, false, {Ts}, {Ts}, '2026-07-02', false, '11b2c4')",
        $"insert into experiment_translations (id, experiment_id, locale, name, purpose, body, seo, created_at, updated_at) values (1, 1, 'en', 'Public Experiment', 'try', 'body', null, {Ts}, {Ts})",
        $"insert into experiment_translations (id, experiment_id, locale, name, purpose, body, seo, created_at, updated_at) values (2, 2, 'en', 'Hidden Experiment', 'try', null, null, {Ts}, {Ts})",
        "insert into experiment_technology (experiment_id, technology_id, \"order\") values (1, 2, 0)",
        $"insert into snippets (id, slug, hidden, show_history, \"order\", created_at, updated_at, published_at, public_id) values (1, 'public-snippet', false, false, 1, {Ts}, {Ts}, '2026-06-01', '21b2c3')",
        $"insert into snippets (id, slug, hidden, show_history, \"order\", created_at, updated_at, published_at, public_id) values (2, 'hidden-snippet', true, false, 2, {Ts}, {Ts}, '2026-06-02', '21b2c4')",
        $"insert into snippet_translations (id, snippet_id, locale, title, description, created_at, updated_at) values (1, 1, 'en', 'Public Snippet', 'desc', {Ts}, {Ts})",
        $"insert into snippet_translations (id, snippet_id, locale, title, description, created_at, updated_at) values (2, 2, 'en', 'Hidden Snippet', null, {Ts}, {Ts})",
        $"insert into snippet_files (id, snippet_id, path, language, content, \"order\", created_at, updated_at) values (1, 1, 'main.cs', 'csharp', 'Console.WriteLine();', 0, {Ts}, {Ts})",
        $"insert into credit_entries (id, url, category, \"order\", created_at, updated_at, is_automatic, active, package_manager, package_name) values (1, 'https://example.test/font', 'font', 1, {Ts}, {Ts}, false, true, null, null)",
        $"insert into credit_entries (id, url, category, \"order\", created_at, updated_at, is_automatic, active, package_manager, package_name) values (2, null, 'reference', 2, {Ts}, {Ts}, false, false, null, null)",
        $"insert into credit_entry_translations (id, credit_entry_id, locale, name, description, created_at, updated_at) values (1, 1, 'en', 'A Font', 'used everywhere', {Ts}, {Ts})",
        $"insert into credit_entry_translations (id, credit_entry_id, locale, name, description, created_at, updated_at) values (2, 2, 'en', 'Inactive Credit', null, {Ts}, {Ts})",
        $"insert into resumes (id, created_at, updated_at) values (1, {Ts}, {Ts})",
        $"insert into resume_translations (id, resume_id, locale, summary, leadership, education, certificates, certifications, publications, recommendations, technical_productions, events, awards, created_at, updated_at) values (1, 1, 'en', 'summary', null, '[{{\"title\":\"BSc\"}}]', null, null, null, null, null, null, null, {Ts}, {Ts})",
        $"insert into resume_skills (id, resume_id, \"order\", created_at, updated_at, topic_id) values (1, 1, 1, {Ts}, {Ts}, 1)",
        "insert into resume_skill_technology (resume_skill_id, technology_id) values (1, 1)",
        $"insert into resume_languages (id, resume_id, language_id, proficiency, \"order\", created_at, updated_at) values (1, 1, 1, 'native', 1, {Ts}, {Ts})",
        "insert into resume_selected_case (resume_id, case_study_id, \"order\") values (1, 1, 0)",
        "insert into resume_selected_case (resume_id, case_study_id, \"order\") values (1, 2, 1)",
        $"insert into relation_types (id, \"key\", family, \"symmetric\", outbound_label_en, outbound_label_pt_br, inbound_label_en, inbound_label_pt_br, created_at, updated_at) values (1, 'authored-by', 'attribution', false, 'authored by', 'escrito por', 'author of', 'autor de', {Ts}, {Ts})",
        $"insert into relation_types (id, \"key\", family, \"symmetric\", outbound_label_en, outbound_label_pt_br, inbound_label_en, inbound_label_pt_br, created_at, updated_at) values (2, 'relates-to', 'context', true, 'relates to', 'relaciona-se com', 'relates to', 'relaciona-se com', {Ts}, {Ts})",
        $"insert into content_relations (id, relation_type_id, subject_type, subject_id, object_type, object_id, note, context, status, visibility, created_at, updated_at) values (1, 1, 'finding', 1, 'topic', 3, null, null, 'verified', 'public', {Ts}, {Ts})",
        $"insert into content_relations (id, relation_type_id, subject_type, subject_id, object_type, object_id, note, context, status, visibility, created_at, updated_at) values (2, 2, 'project', 1, 'writing', 1, 'see also', null, 'verified', null, {Ts}, {Ts})",
        $"insert into content_relations (id, relation_type_id, subject_type, subject_id, object_type, object_id, note, context, status, visibility, created_at, updated_at) values (3, 2, 'finding', 1, 'finding', 4, null, null, 'verified', 'public', {Ts}, {Ts})",
        $"insert into audit_log (id, auditable_type, auditable_id, action, old_values, new_values, request_id, ip, user_agent, created_at) values (1, 'App\\Models\\ProjectTranslation', 1, 'updated', '{{\"name\":\"Old\"}}', '{{\"name\":\"Public Project\"}}', null, null, null, '2026-08-02 09:00:00')",
        "insert into audit_log (id, auditable_type, auditable_id, action, old_values, new_values, request_id, ip, user_agent, created_at) values (2, 'App\\Models\\ProjectTranslation', 1, 'updated', '{\"status\":\"draft\"}', '{\"status\":\"active\"}', null, null, null, null)",
        $"insert into nav_items (id, route_name, parent_id, placement, sidebar_group, \"order\", created_at, updated_at) values (1, 'writing', null, 'sidebar', 1, 1, {Ts}, {Ts})",
        $"insert into nav_items (id, route_name, parent_id, placement, sidebar_group, \"order\", created_at, updated_at) values (2, 'about', null, 'sidebar', 2, 1, {Ts}, {Ts})",
        $"insert into nav_items (id, route_name, parent_id, placement, sidebar_group, \"order\", created_at, updated_at) values (3, 'projects', 2, 'sidebar', 2, 1, {Ts}, {Ts})",
        $"insert into nav_items (id, route_name, parent_id, placement, sidebar_group, \"order\", created_at, updated_at) values (4, 'follow', null, 'footer', null, 1, {Ts}, {Ts})",
        $"insert into nav_item_translations (id, nav_item_id, locale, label, created_at, updated_at) values (1, 1, 'en', 'writing', {Ts}, {Ts})",
        $"insert into nav_item_translations (id, nav_item_id, locale, label, created_at, updated_at) values (2, 1, 'pt-BR', 'escritos', {Ts}, {Ts})",
        $"insert into nav_item_translations (id, nav_item_id, locale, label, created_at, updated_at) values (3, 2, 'en', 'about', {Ts}, {Ts})",
        $"insert into nav_item_translations (id, nav_item_id, locale, label, created_at, updated_at) values (4, 3, 'en', 'projects', {Ts}, {Ts})",
        $"insert into nav_item_translations (id, nav_item_id, locale, label, created_at, updated_at) values (5, 4, 'en', 'follow', {Ts}, {Ts})",
    ];

    internal static void Apply(DbConnection connection)
    {
        foreach (var statement in Statements)
        {
            using var command = connection.CreateCommand();
            command.CommandText = statement;
            command.ExecuteNonQuery();
        }
    }
}
