import type { SxProps, Theme } from '@mui/material/styles';

export const linkVariants: Record<string, SxProps<Theme>> = {
  sectionHeadingGrid: {
    gridRow: { xs: 3, sm: 1 },
    gridColumn: { xs: 1, sm: 2 },
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    whiteSpace: 'nowrap',
    fontSize: '.9rem',
    fontWeight: 600,
  },
  creditEntryItem: { fontWeight: 700 },
  statusActions: { py: 1 },
  editableItemName: { fontWeight: 700 },
  recommendationEntry: { fontWeight: 700 },
  experimentSource: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    fontWeight: 600,
  },
  experimentRow: {
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    gap: 'var(--site-space-3)',
    p: 'var(--site-inset-card)',
    border: 'var(--site-border-width) solid var(--site-border)',
    borderLeft: 'var(--site-feed-accent-w) solid var(--site-primary)',
    backgroundColor: 'var(--site-surface)',
    '&:hover .experiment-title': { color: 'secondary.main' },
  },
  projectDetailContent: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    fontWeight: 600,
  },
  siteBrand: {
    display: 'inline-block',
    margin: 0,
    color: 'var(--site-text-primary)',
    fontFamily: 'var(--site-font-logo)',
    fontSize: 'var(--site-text-2xl)',
    fontWeight: 'var(--site-weight-bold)',
    lineHeight: 'var(--site-leading-tight)',
    textDecoration: 'none',
  },
  readCaseLink: { display: 'inline-flex', alignItems: 'center', gap: 0.75, fontWeight: 650 },
  revealDialogRevealed: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'var(--site-space-2)',
    fontWeight: 600,
  },
  protectedEmailInlineRevealed: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'var(--site-space-2)',
    fontWeight: 600,
  },
  resumeCaseLink: { color: 'inherit', fontWeight: 700, textDecoration: 'none' },
  resumeCaseAction: { display: 'inline-block', fontSize: '0.875rem', marginTop: '0.75rem' },
  externalLink: { display: 'inline-flex', alignItems: 'center', gap: 0.75 },
  protectedEmailInlineTrigger: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'var(--site-space-2)',
    border: 0,
    background: 'none',
    cursor: 'pointer',
    font: 'inherit',
    fontWeight: 600,
    p: 0,
  },
  protectedEmailInlineTriggerBusy: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'var(--site-space-2)',
    border: 0,
    background: 'none',
    cursor: 'progress',
    font: 'inherit',
    fontWeight: 600,
    p: 0,
  },
};
