import assert from 'node:assert/strict';
import { mkdtemp, readdir, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { parseGenerateCommandOptions } from '../src/cli.ts';
import { loadProfileReadmeSource, type ProfileReadmeSource } from '../src/content.ts';
import { assertSafeOutputPath } from '../src/filesystem.ts';
import { generateProfileReadme } from '../src/generate.ts';
import { renderProfileReadme } from '../src/render.ts';

const source: ProfileReadmeSource = {
  profile: {
    name: 'Gabriel Antunes',
    title: 'Solutions developer',
    location: 'Rondônia, Brazil · remote',
    birthCity: 'Ji-Paraná, Rondônia, Brazil',
    description: 'I solve problems with systems, data and tools.',
    interests: '',
    learning: '',
    personalInterests: [],
    trajectory: [],
    milestones: [],
  },
  resume: {
    summary: '',
    skills: [],
    languages: [],
    selectedCases: [],
    leadership: [],
    education: [],
    certificates: [],
    certifications: [],
    publications: [],
    recommendations: [],
    technicalProductions: [],
    events: [],
    awards: [],
  },
  site: {
    shortName: 'GA',
    copyrightTemplate: '',
    maintenanceEnabled: false,
    maintenance: { eyebrow: '', title: '', description: '' },
    contact: { available: false, hasEmail: false, profiles: [] },
  },
  email: '',
};

test('loads canonical English content through @portfolio/content', async () => {
  const loaded = await loadProfileReadmeSource();

  assert.equal(loaded.profile.name, 'Gabriel Antunes');
  assert.equal(loaded.resume.languages[0]?.name, 'Portuguese (Brazil)');
});

test('renders the public README deterministically from the English canonical source', () => {
  const populated: ProfileReadmeSource = {
    ...source,
    profile: {
      ...source.profile,
      interests: 'Systems and developer tools.',
      learning: 'Computing and mathematics.',
      personalInterests: ['Coffee and code.'],
      _contentEditing: {
        query: 'secret',
        variables: { relativePath: 'profile.json' },
        data: {},
        root: 'profile',
      },
    },
    resume: {
      ...source.resume,
      summary: 'I work across backend systems and infrastructure.',
      languages: [
        { code: 'pt-BR', name: 'Portuguese (Brazil)', proficiency: 'native' },
        { code: 'en', name: 'English' },
      ],
      skills: [{ label: 'Languages', items: ['TypeScript', 'Go'] }],
    },
    site: {
      ...source.site,
      portfolioUrl: 'https://portfolio.example.com',
      contact: {
        available: true,
        hasEmail: true,
        profiles: [
          { platform: 'github', url: 'https://github.com/guesant' },
          { platform: 'linkedin', url: 'https://linkedin.com/in/gabriel' },
          { platform: 'lattes', url: 'http://lattes.cnpq.br/5981427817317311' },
          { platform: 'orcid', url: 'https://orcid.org/0009-0009-0221-943X' },
          { platform: 'instagram', url: 'https://instagram.com/guesant' },
          { platform: 'gitlab', url: 'https://gitlab.com/guesant' },
        ],
      },
    },
    email: 'gabriel@example.com',
  };

  const expected = `<!-- Generated by guesant/portfolio. Do not edit this file manually. -->

# Hello, my name is Gabriel Antunes 👋

**Solutions developer**

I solve problems with systems, data and tools.

I work across backend systems and infrastructure.

## Location

Rondônia, Brazil · remote

## Born in

Ji-Paraná, Rondônia, Brazil 🇧🇷

## Interests

**Technical interests:** Systems and developer tools.

**Learning:** Computing and mathematics.

## Hobbies

- Coffee and code.

## Languages

- Portuguese (Brazil) — Native
- English

## Stacks

### Languages

TypeScript · Go

## Social

- [gabriel@example.com](mailto:gabriel%40example.com)
- [LinkedIn](https://linkedin.com/in/gabriel)
- [GitHub](https://github.com/guesant)
- [Lattes](http://lattes.cnpq.br/5981427817317311)
- [ORCID](https://orcid.org/0009-0009-0221-943X)
- [Instagram](https://instagram.com/guesant)
- [GitLab](https://gitlab.com/guesant)

## Portfolio

[Visit my portfolio](https://portfolio.example.com/)
`;

  assert.equal(renderProfileReadme(populated), expected);
  assert.equal(renderProfileReadme(populated), expected);
  assert.doesNotMatch(renderProfileReadme(populated), /secret|_contentEditing/);
});

test('omits empty sections and escapes dynamic Markdown and URLs', () => {
  const rendered = renderProfileReadme({
    ...source,
    profile: {
      ...source.profile,
      name: 'A *developer* <script>',
      title: '',
      description: '',
    },
    site: {
      ...source.site,
      contact: {
        available: true,
        hasEmail: false,
        profiles: [
          { platform: 'github', url: 'javascript:alert(1)' },
          { platform: 'linkedin', url: 'https://example.com/a_(b)?q=[x]' },
        ],
      },
    },
    email: '',
  });

  assert.ok(rendered.includes('# Hello, my name is A \\*developer\\* &lt;script&gt; 👋'));
  assert.match(rendered, /\[LinkedIn\]\(https:\/\/example\.com\/a_%28b%29\?q=%5Bx%5D\)/);
  assert.doesNotMatch(rendered, /## Interests|## Languages|## Stacks/);
  assert.doesNotMatch(rendered, /javascript:|<script>/);
  assert.ok(rendered.endsWith('\n'));
});

test('requires an explicit safe output and writes it atomically', async () => {
  assert.deepEqual(parseGenerateCommandOptions(['--output', '/tmp/profile/README.md']), {
    outputPath: '/tmp/profile/README.md',
  });
  assert.deepEqual(parseGenerateCommandOptions(['--', '--output', '/tmp/profile/README.md']), {
    outputPath: '/tmp/profile/README.md',
  });
  assert.throws(() => parseGenerateCommandOptions([]), /Usage:/);
  assert.throws(() => parseGenerateCommandOptions(['--output']), /Usage:/);
  assert.throws(
    () => assertSafeOutputPath('/workspace/README.md', '/workspace/README.md'),
    /Refusing to overwrite/,
  );

  const directory = await mkdtemp(path.join(tmpdir(), 'profile-sync-'));
  const outputPath = path.join(directory, 'README.md');
  try {
    const generated = await generateProfileReadme({
      outputPath,
      workspaceReadmePath: '/workspace/README.md',
      source,
    });

    assert.equal(await readFile(outputPath, 'utf8'), generated);
    assert.deepEqual(await readdir(directory), ['README.md']);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
