export const sidebarActionSx = {
  width: '100%',
  minWidth: 0,
  height: '2rem',
  minHeight: '2rem',
  justifyContent: 'flex-start',
  paddingInline: 'var(--site-space-3)',
  paddingBlock: 'var(--site-space-1)',
  border: 'var(--site-border-width) solid',
  borderColor: 'divider',
  borderRadius: 'var(--site-radius)',
  color: 'text.secondary',
  fontSize: 'var(--site-text-action)',
  fontWeight: 500,
  lineHeight: 'var(--site-leading-normal)',
  textAlign: 'left',
  '& .MuiButton-startIcon': {
    marginLeft: 0,
    marginRight: 'var(--site-space-2)',
  },
  '&:hover': {
    color: 'secondary.main',
    bgcolor: 'action.hover',
    borderColor: 'secondary.main',
  },
} as const;
