import type { SxProps, Theme } from '@mui/material/styles';

export const cardVariants: Record<string, SxProps<Theme>> = {
  caseCard: {
    p: 'var(--site-inset-card)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--site-space-2)',
    borderLeft: 'var(--site-feed-accent-w) solid var(--site-primary)',
    bgcolor: 'var(--site-surface)',
    transition:
      'border-color var(--site-duration-short-4), background-color var(--site-duration-short-4)',
    '&:hover': {
      borderColor: 'var(--site-primary-hover)',
      bgcolor: 'var(--site-surface-hover)',
    },
    '&:hover .case-title': { color: 'secondary.main' },
  },
  renderFollowEntryCard: {
    p: 'var(--site-inset-card)',
    color: 'inherit',
    textDecoration: 'none',
    borderLeft: 'var(--site-feed-accent-w) solid var(--site-primary)',
  },
  renderFollowEntryCard2: {
    p: 'var(--site-inset-card)',
    borderLeft: 'var(--site-feed-accent-w) solid var(--site-primary)',
  },
  catalogEntry: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--site-space-2)',
    p: 'var(--site-inset-card)',
    borderLeft: 'var(--site-feed-accent-w) solid var(--site-primary)',
    color: 'inherit',
    textDecoration: 'none',
  },
  featuredCaseCard: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '5fr 7fr' },
    minHeight: { md: '21.5rem' },
    overflow: 'hidden',
    bgcolor: 'background.paper',
  },
  referenceCard: {
    p: 'var(--site-inset-card)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--site-space-2)',
    bgcolor: 'var(--site-surface)',
    borderLeft: 'var(--site-feed-accent-w) solid var(--site-primary)',
    borderColor: 'var(--site-border)',
    transition:
      'border-color var(--site-duration-short-4), background-color var(--site-duration-short-4)',
    '&:hover .reference-card-title': { color: 'secondary.main' },
    '&:hover': {
      borderColor: 'var(--site-primary-hover)',
      bgcolor: 'var(--site-surface-hover)',
    },
  },
  feedCard: {
    position: 'relative',
    padding:
      'var(--site-space-4) var(--site-space-5) var(--site-space-5) calc(var(--site-space-5) + var(--site-feed-accent-w))',
    display: 'flex',
    flexDirection: 'column',
    borderColor: 'divider',
    border: 'var(--site-border-width) solid var(--site-border)',
    borderRadius: 0,
    gap: 'var(--site-space-2)',
    overflow: 'hidden',
    backgroundColor: 'var(--site-surface)',
    boxShadow: 'none',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: '0 auto 0 0',
      width: 'var(--site-feed-accent-w)',
      backgroundColor: 'var(--site-primary)',
    },
    '&:hover .content-feed-title': { color: 'secondary.main' },
  },
  projectCardHighlighted: {
    minHeight: '17rem',
    p: 3,
    display: 'flex',
    flexDirection: 'column',
    transition: 'border-color .2s, background-color .2s, transform .2s',
    bgcolor: '#EAF2FA',
    borderColor: 'rgba(29,95,167,.28)',
    '&:hover .project-card-title': { color: 'secondary.main' },
    '&:hover': {
      borderColor: 'rgba(29,95,167,.55)',
      bgcolor: '#E1EDF8',
      transform: 'translateY(-2px)',
    },
  },
  projectCardPlain: {
    minHeight: '17rem',
    p: 3,
    display: 'flex',
    flexDirection: 'column',
    transition: 'border-color .2s, background-color .2s, transform .2s',
    bgcolor: 'rgba(255,255,255,.72)',
    borderColor: 'divider',
    '&:hover .project-card-title': { color: 'secondary.main' },
    '&:hover': {
      borderColor: 'rgba(29,95,167,.55)',
      bgcolor: 'background.paper',
      transform: 'translateY(-2px)',
    },
  },
  caseLinkCardCompact: {
    display: 'flex',
    flexDirection: 'column',
    p: 3,
    color: 'text.primary',
    textDecoration: 'none',
    bgcolor: 'rgba(255,255,255,.56)',
    minHeight: '14rem',
    transition: 'border-color .2s, background-color .2s, transform .2s',
    '&:hover': {
      borderColor: 'rgba(29,95,167,.55)',
      bgcolor: 'background.paper',
      transform: 'translateY(-2px)',
    },
    '&:hover .case-link-title': { color: 'secondary.main' },
  },
  caseLinkCardFull: {
    display: 'flex',
    flexDirection: 'column',
    p: 3,
    color: 'text.primary',
    textDecoration: 'none',
    bgcolor: 'rgba(255,255,255,.56)',
    minHeight: 'auto',
    transition: 'border-color .2s, background-color .2s, transform .2s',
    '&:hover': {
      borderColor: 'rgba(29,95,167,.55)',
      bgcolor: 'background.paper',
      transform: 'translateY(-2px)',
    },
    '&:hover .case-link-title': { color: 'secondary.main' },
  },
};
