<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Portfolio.Blazor.UI</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.11" />
    <PackageReference Include="BlazorBlueprint.Components" Version="3.16.0" />
    <ProjectReference Include="..\Portfolio.Blazor.Core\Portfolio.Blazor.Core.csproj" />
  </ItemGroup>
</Project>
