import {
  SiBluesky,
  SiBootstrap,
  SiBun,
  SiCss,
  SiDocker,
  SiDotnet,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGitlab,
  SiGnu,
  SiGnubash,
  SiGo,
  SiGooglescholar,
  SiGraphql,
  SiHelm,
  SiHtml5,
  SiInstagram,
  SiJavascript,
  SiK3s,
  SiKubernetes,
  SiLinux,
  SiMacos,
  SiMastodon,
  SiNativescript,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiNx,
  SiOpenapiinitiative,
  SiOrcid,
  SiPfsense,
  SiPhp,
  SiPnpm,
  SiPortainer,
  SiPostgresql,
  SiPrisma,
  SiProxmox,
  SiPuppeteer,
  SiReact,
  SiRedux,
  SiResearchgate,
  SiSqlite,
  SiTypescript,
  SiVim,
  SiVitest,
  SiVuedotjs,
  SiWebstorm,
  SiWordpress,
  SiYii,
} from '@icons-pack/react-simple-icons';
import type { IconType } from '@icons-pack/react-simple-icons';

export const brands = {
  bluesky: SiBluesky,
  bootstrap: SiBootstrap,
  bun: SiBun,
  css: SiCss,
  docker: SiDocker,
  dotnet: SiDotnet,
  git: SiGit,
  github: SiGithub,
  githubactions: SiGithubactions,
  gitlab: SiGitlab,
  gnu: SiGnu,
  gnubash: SiGnubash,
  go: SiGo,
  googlescholar: SiGooglescholar,
  graphql: SiGraphql,
  helm: SiHelm,
  html5: SiHtml5,
  instagram: SiInstagram,
  javascript: SiJavascript,
  k3s: SiK3s,
  kubernetes: SiKubernetes,
  linux: SiLinux,
  macos: SiMacos,
  mastodon: SiMastodon,
  nativescript: SiNativescript,
  nestjs: SiNestjs,
  nextdotjs: SiNextdotjs,
  nodedotjs: SiNodedotjs,
  npm: SiNpm,
  nx: SiNx,
  openapiinitiative: SiOpenapiinitiative,
  orcid: SiOrcid,
  pfsense: SiPfsense,
  php: SiPhp,
  pnpm: SiPnpm,
  portainer: SiPortainer,
  postgresql: SiPostgresql,
  prisma: SiPrisma,
  proxmox: SiProxmox,
  puppeteer: SiPuppeteer,
  react: SiReact,
  redux: SiRedux,
  researchgate: SiResearchgate,
  sqlite: SiSqlite,
  typescript: SiTypescript,
  vim: SiVim,
  vitest: SiVitest,
  vuedotjs: SiVuedotjs,
  webstorm: SiWebstorm,
  wordpress: SiWordpress,
  yii: SiYii,
} satisfies Record<string, IconType>;

export type BrandName = keyof typeof brands;
