import {
  SiBlueskyHex,
  SiBootstrapHex,
  SiBunHex,
  SiCssHex,
  SiDockerHex,
  SiDotnetHex,
  SiGitHex,
  SiGithubHex,
  SiGithubactionsHex,
  SiGitlabHex,
  SiGnuHex,
  SiGnubashHex,
  SiGoHex,
  SiGooglescholarHex,
  SiGraphqlHex,
  SiHelmHex,
  SiHtml5Hex,
  SiInstagramHex,
  SiJavascriptHex,
  SiK3sHex,
  SiKubernetesHex,
  SiLinuxHex,
  SiMacosHex,
  SiMastodonHex,
  SiNativescriptHex,
  SiNestjsHex,
  SiNextdotjsHex,
  SiNodedotjsHex,
  SiNpmHex,
  SiNxHex,
  SiOpenapiinitiativeHex,
  SiOrcidHex,
  SiPfsenseHex,
  SiPhpHex,
  SiPnpmHex,
  SiPortainerHex,
  SiPostgresqlHex,
  SiPrismaHex,
  SiProxmoxHex,
  SiPuppeteerHex,
  SiReactHex,
  SiReduxHex,
  SiResearchgateHex,
  SiSqliteHex,
  SiTypescriptHex,
  SiVimHex,
  SiVitestHex,
  SiVuedotjsHex,
  SiWebstormHex,
  SiWordpressHex,
  SiYiiHex,
} from '@icons-pack/react-simple-icons';
import type { BrandName } from './brand-icon-data';

export const brandColors: Record<BrandName, string> = {
  bluesky: SiBlueskyHex,
  bootstrap: SiBootstrapHex,
  bun: SiBunHex,
  css: SiCssHex,
  docker: SiDockerHex,
  dotnet: SiDotnetHex,
  git: SiGitHex,
  github: SiGithubHex,
  githubactions: SiGithubactionsHex,
  gitlab: SiGitlabHex,
  gnu: SiGnuHex,
  gnubash: SiGnubashHex,
  go: SiGoHex,
  googlescholar: SiGooglescholarHex,
  graphql: SiGraphqlHex,
  helm: SiHelmHex,
  html5: SiHtml5Hex,
  instagram: SiInstagramHex,
  javascript: SiJavascriptHex,
  k3s: SiK3sHex,
  kubernetes: SiKubernetesHex,
  linux: SiLinuxHex,
  macos: SiMacosHex,
  mastodon: SiMastodonHex,
  nativescript: SiNativescriptHex,
  nestjs: SiNestjsHex,
  nextdotjs: SiNextdotjsHex,
  nodedotjs: SiNodedotjsHex,
  npm: SiNpmHex,
  nx: SiNxHex,
  openapiinitiative: SiOpenapiinitiativeHex,
  orcid: SiOrcidHex,
  pfsense: SiPfsenseHex,
  php: SiPhpHex,
  pnpm: SiPnpmHex,
  portainer: SiPortainerHex,
  postgresql: SiPostgresqlHex,
  prisma: SiPrismaHex,
  proxmox: SiProxmoxHex,
  puppeteer: SiPuppeteerHex,
  react: SiReactHex,
  redux: SiReduxHex,
  researchgate: SiResearchgateHex,
  sqlite: SiSqliteHex,
  typescript: SiTypescriptHex,
  vim: SiVimHex,
  vitest: SiVitestHex,
  vuedotjs: SiVuedotjsHex,
  webstorm: SiWebstormHex,
  wordpress: SiWordpressHex,
  yii: SiYiiHex,
};
