import {
  type SimpleIcon,
  siBluesky,
  siBootstrap,
  siBun,
  siCss,
  siDocker,
  siDotnet,
  siGit,
  siGithub,
  siGithubactions,
  siGitlab,
  siGnu,
  siGnubash,
  siGo,
  siGooglescholar,
  siGraphql,
  siHelm,
  siHtml5,
  siInstagram,
  siJavascript,
  siK3s,
  siKubernetes,
  siLinux,
  siMacos,
  siMastodon,
  siNativescript,
  siNestjs,
  siNextdotjs,
  siNodedotjs,
  siNpm,
  siNx,
  siOpenapiinitiative,
  siOrcid,
  siPfsense,
  siPhp,
  siPnpm,
  siPortainer,
  siPostgresql,
  siPrisma,
  siProxmox,
  siPuppeteer,
  siReact,
  siRedux,
  siResearchgate,
  siSqlite,
  siTypescript,
  siVim,
  siVitest,
  siVuedotjs,
  siWebstorm,
  siWordpress,
  siYii,
} from 'simple-icons';
import type { BrandName } from './brand-icon-name';

export const brands: Record<BrandName, SimpleIcon> = {
  bluesky: siBluesky,
  bootstrap: siBootstrap,
  bun: siBun,
  css: siCss,
  docker: siDocker,
  dotnet: siDotnet,
  git: siGit,
  github: siGithub,
  githubactions: siGithubactions,
  gitlab: siGitlab,
  gnu: siGnu,
  gnubash: siGnubash,
  go: siGo,
  googlescholar: siGooglescholar,
  graphql: siGraphql,
  helm: siHelm,
  html5: siHtml5,
  instagram: siInstagram,
  javascript: siJavascript,
  k3s: siK3s,
  kubernetes: siKubernetes,
  linux: siLinux,
  macos: siMacos,
  mastodon: siMastodon,
  nativescript: siNativescript,
  nestjs: siNestjs,
  nextdotjs: siNextdotjs,
  nodedotjs: siNodedotjs,
  npm: siNpm,
  nx: siNx,
  openapiinitiative: siOpenapiinitiative,
  orcid: siOrcid,
  pfsense: siPfsense,
  php: siPhp,
  pnpm: siPnpm,
  portainer: siPortainer,
  postgresql: siPostgresql,
  prisma: siPrisma,
  proxmox: siProxmox,
  puppeteer: siPuppeteer,
  react: siReact,
  redux: siRedux,
  researchgate: siResearchgate,
  sqlite: siSqlite,
  typescript: siTypescript,
  vim: siVim,
  vitest: siVitest,
  vuedotjs: siVuedotjs,
  webstorm: siWebstorm,
  wordpress: siWordpress,
  yii: siYii,
};
