import {
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Book,
  Bookmark,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  CircleDashed,
  CircleHelp,
  Clapperboard,
  Clock,
  Compass,
  Copy,
  Download,
  ExternalLink,
  FileText,
  FolderGit2,
  GitBranch,
  Globe,
  GraduationCap,
  Home,
  Languages,
  LayoutGrid,
  Lightbulb,
  ListVideo,
  Mail,
  Menu,
  MessagesSquare,
  Moon,
  MoreHorizontal,
  Newspaper,
  PenLine,
  PlayCircle,
  Podcast,
  Rss,
  ScrollText,
  Search,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  StarOff,
  Sun,
  Tag,
  Trash2,
  Tv,
  User,
  Video,
  Wrench,
  X,
  XCircle,
  type LucideProps,
} from 'lucide-react';
import type { ComponentType } from 'react';
import type { IconName } from './icon-name';

export const icons: Record<IconName, ComponentType<LucideProps>> = {
  arrow: ArrowRight,
  'arrow-left': ArrowLeft,
  menu: Menu,
  close: X,
  mail: Mail,
  document: FileText,
  external: ExternalLink,
  'north-east': ArrowUpRight,
  problem: CircleHelp,
  solution: Lightbulb,
  evolution: GitBranch,
  'chevron-down': ChevronDown,
  home: Home,
  briefcase: Briefcase,
  'graduation-cap': GraduationCap,
  copy: Copy,
  check: Check,
  search: Search,
  rss: Rss,
  filter: SlidersHorizontal,
  'layout-grid': LayoutGrid,
  'pen-line': PenLine,
  sparkles: Sparkles,
  user: User,
  tag: Tag,
  star: Star,
  'star-off': StarOff,
  calendar: Calendar,
  compass: Compass,
  book: Book,
  newspaper: Newspaper,
  'scroll-text': ScrollText,
  'folder-git': FolderGit2,
  globe: Globe,
  'book-open': BookOpen,
  wrench: Wrench,
  video: Video,
  'list-video': ListVideo,
  tv: Tv,
  podcast: Podcast,
  clapperboard: Clapperboard,
  'more-horizontal': MoreHorizontal,
  bookmark: Bookmark,
  clock: Clock,
  'check-circle': CheckCircle2,
  'x-circle': XCircle,
  archive: Archive,
  'circle-dashed': CircleDashed,
  download: Download,
  'shopping-cart': ShoppingCart,
  'play-circle': PlayCircle,
  languages: Languages,
  'messages-square': MessagesSquare,
  building: Building2,
  moon: Moon,
  sun: Sun,
  trash: Trash2,
};
