import * as LucideIcons from 'lucide-react';
import type { LucideProps } from 'lucide-react';
import type { ComponentType } from 'react';

export const icons = {
  arrow: LucideIcons.ArrowRight,
  'arrow-left': LucideIcons.ArrowLeft,
  menu: LucideIcons.Menu,
  close: LucideIcons.X,
  mail: LucideIcons.Mail,
  document: LucideIcons.FileText,
  external: LucideIcons.ExternalLink,
  'north-east': LucideIcons.ArrowUpRight,
  problem: LucideIcons.CircleHelp,
  solution: LucideIcons.Lightbulb,
  evolution: LucideIcons.GitBranch,
  'chevron-down': LucideIcons.ChevronDown,
  home: LucideIcons.Home,
  briefcase: LucideIcons.Briefcase,
  'graduation-cap': LucideIcons.GraduationCap,
  copy: LucideIcons.Copy,
  check: LucideIcons.Check,
  search: LucideIcons.Search,
  rss: LucideIcons.Rss,
  filter: LucideIcons.SlidersHorizontal,
  'layout-grid': LucideIcons.LayoutGrid,
  'pen-line': LucideIcons.PenLine,
  sparkles: LucideIcons.Sparkles,
  user: LucideIcons.User,
  tag: LucideIcons.Tag,
  star: LucideIcons.Star,
  'star-off': LucideIcons.StarOff,
  calendar: LucideIcons.Calendar,
  compass: LucideIcons.Compass,
  book: LucideIcons.Book,
  newspaper: LucideIcons.Newspaper,
  'scroll-text': LucideIcons.ScrollText,
  'folder-git': LucideIcons.FolderGit2,
  globe: LucideIcons.Globe,
  'book-open': LucideIcons.BookOpen,
  wrench: LucideIcons.Wrench,
  video: LucideIcons.Video,
  'list-video': LucideIcons.ListVideo,
  tv: LucideIcons.Tv,
  podcast: LucideIcons.Podcast,
  clapperboard: LucideIcons.Clapperboard,
  'more-horizontal': LucideIcons.MoreHorizontal,
  bookmark: LucideIcons.Bookmark,
  clock: LucideIcons.Clock,
  'check-circle': LucideIcons.CheckCircle2,
  'x-circle': LucideIcons.XCircle,
  archive: LucideIcons.Archive,
  'circle-dashed': LucideIcons.CircleDashed,
  download: LucideIcons.Download,
  'shopping-cart': LucideIcons.ShoppingCart,
  'play-circle': LucideIcons.PlayCircle,
  languages: LucideIcons.Languages,
  'messages-square': LucideIcons.MessagesSquare,
  building: LucideIcons.Building2,
  moon: LucideIcons.Moon,
  sun: LucideIcons.Sun,
  trash: LucideIcons.Trash2,
} satisfies Record<string, ComponentType<LucideProps>>;

export type IconName = keyof typeof icons;
