--
-- PostgreSQL database dump
--


-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', 'public', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id integer NOT NULL,
    auditable_type text NOT NULL,
    auditable_id integer NOT NULL,
    action text NOT NULL,
    old_values text,
    new_values text,
    request_id text,
    ip text,
    user_agent text,
    created_at timestamp without time zone
);


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_requests (
    request_id text NOT NULL,
    method text NOT NULL,
    path text NOT NULL,
    ip text,
    user_agent text,
    created_at timestamp without time zone
);


--
-- Name: case_studies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.case_studies (
    id integer NOT NULL,
    slug text NOT NULL,
    public_id character varying(6) NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    "order" integer NOT NULL,
    href text,
    external boolean DEFAULT false NOT NULL,
    visual text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    nda boolean DEFAULT false NOT NULL,
    published_at date,
    show_history boolean DEFAULT false NOT NULL
);


--
-- Name: case_studies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.case_studies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.case_studies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: case_study_technology; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.case_study_technology (
    case_study_id integer NOT NULL,
    technology_id integer NOT NULL,
    "order" integer DEFAULT 0 NOT NULL
);


--
-- Name: case_study_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.case_study_translations (
    id integer NOT NULL,
    case_study_id integer NOT NULL,
    locale text NOT NULL,
    title text NOT NULL,
    status text,
    meta text,
    summary text,
    context text,
    role text,
    result text,
    metrics text,
    body text,
    seo text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: case_study_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.case_study_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.case_study_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_profiles (
    id integer NOT NULL,
    site_settings_id integer NOT NULL,
    platform text NOT NULL,
    label text,
    url text NOT NULL,
    "order" integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: contact_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_relations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_relations (
    id integer NOT NULL,
    relation_type_id integer NOT NULL,
    subject_type text NOT NULL,
    subject_id integer NOT NULL,
    object_type text NOT NULL,
    object_id integer NOT NULL,
    note text,
    context text,
    status text DEFAULT 'verified'::text,
    visibility text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: content_relations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content_relations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_relations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_revisions (
    id integer NOT NULL,
    version bigint NOT NULL,
    updated_at timestamp without time zone
);


--
-- Name: credit_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_entries (
    id integer NOT NULL,
    url text,
    category text NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    is_automatic boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    package_manager text,
    package_name text
);


--
-- Name: credit_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: credit_entry_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_entry_translations (
    id integer NOT NULL,
    credit_entry_id integer NOT NULL,
    locale text NOT NULL,
    name text NOT NULL,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: credit_entry_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_entry_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_entry_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: experiment_technology; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experiment_technology (
    experiment_id integer NOT NULL,
    technology_id integer NOT NULL,
    "order" integer DEFAULT 0 NOT NULL
);


--
-- Name: experiment_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experiment_translations (
    id integer NOT NULL,
    experiment_id integer NOT NULL,
    locale text NOT NULL,
    name text NOT NULL,
    purpose text NOT NULL,
    body text,
    seo text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: experiment_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.experiment_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experiment_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: experiments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experiments (
    id integer NOT NULL,
    slug text NOT NULL,
    public_id character varying(6) NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    "order" integer NOT NULL,
    href text,
    external boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    published_at date,
    show_history boolean DEFAULT false NOT NULL
);


--
-- Name: experiments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.experiments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experiments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: language_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.language_translations (
    id integer NOT NULL,
    language_id integer NOT NULL,
    locale text NOT NULL,
    name text NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: language_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.language_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.language_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.languages (
    id integer NOT NULL,
    slug text NOT NULL,
    "order" integer NOT NULL,
    code text NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: languages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.languages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nav_item_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nav_item_translations (
    id integer NOT NULL,
    nav_item_id integer NOT NULL,
    locale text NOT NULL,
    label text NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: nav_item_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nav_item_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nav_item_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nav_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nav_items (
    id integer NOT NULL,
    route_name text NOT NULL,
    parent_id integer,
    placement text,
    sidebar_group integer,
    "order" integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: nav_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nav_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nav_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: page_featured_case; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.page_featured_case (
    page_id integer NOT NULL,
    case_study_id integer NOT NULL,
    "order" integer
);


--
-- Name: page_featured_project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.page_featured_project (
    page_id integer NOT NULL,
    project_id integer NOT NULL,
    "order" integer
);


--
-- Name: page_featured_writing; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.page_featured_writing (
    page_id integer NOT NULL,
    writing_id integer NOT NULL,
    "order" integer
);


--
-- Name: page_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.page_translations (
    id integer NOT NULL,
    page_id integer NOT NULL,
    locale text NOT NULL,
    fields text NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: page_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.page_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.page_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pages (
    id integer NOT NULL,
    slug text NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    hidden boolean DEFAULT false NOT NULL
);


--
-- Name: pages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profile_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_translations (
    id integer NOT NULL,
    profile_id integer NOT NULL,
    locale text NOT NULL,
    title text,
    location text,
    birth_city text,
    description text,
    interests text,
    learning text,
    personal_interests text,
    trajectory text,
    milestones text,
    fortunes text,
    personal_facts text,
    personal_things text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: profile_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profile_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    id integer NOT NULL,
    name text,
    birth_date date,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    hidden boolean DEFAULT false NOT NULL
);


--
-- Name: profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_technology; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_technology (
    project_id integer NOT NULL,
    technology_id integer NOT NULL,
    "order" integer DEFAULT 0 NOT NULL
);


--
-- Name: project_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_translations (
    id integer NOT NULL,
    project_id integer NOT NULL,
    locale text NOT NULL,
    name text NOT NULL,
    purpose text NOT NULL,
    problem text,
    current_focus text,
    status text,
    metrics text,
    body text,
    seo text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: project_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id integer NOT NULL,
    slug text NOT NULL,
    public_id character varying(6) NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    "order" integer NOT NULL,
    href text,
    external boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    nda boolean DEFAULT false NOT NULL,
    published_at date,
    show_history boolean DEFAULT false NOT NULL
);


--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reference_collection_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reference_collection_item (
    reference_collection_id integer NOT NULL,
    resource_id integer NOT NULL,
    note text,
    "order" integer
);


--
-- Name: reference_collection_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reference_collection_translations (
    id integer NOT NULL,
    reference_collection_id integer NOT NULL,
    locale text NOT NULL,
    title text NOT NULL,
    description text,
    intro text,
    seo text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: reference_collection_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reference_collection_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reference_collection_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reference_collections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reference_collections (
    id integer NOT NULL,
    slug text NOT NULL,
    public_id character varying(6) NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    "order" integer NOT NULL,
    image text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    published_at date
);


--
-- Name: reference_collections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reference_collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reference_collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: relation_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.relation_types (
    id integer NOT NULL,
    key text NOT NULL,
    family text NOT NULL,
    "symmetric" boolean NOT NULL,
    outbound_label_en text NOT NULL,
    outbound_label_pt_br text NOT NULL,
    inbound_label_en text NOT NULL,
    inbound_label_pt_br text NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: relation_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.relation_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.relation_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resource_identifiers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_identifiers (
    id integer NOT NULL,
    resource_id integer NOT NULL,
    kind text NOT NULL,
    value text NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: resource_identifiers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resource_identifiers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_identifiers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resource_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_links (
    id integer NOT NULL,
    resource_id integer NOT NULL,
    url text NOT NULL,
    label text,
    platform text,
    purpose text,
    is_primary boolean DEFAULT false NOT NULL,
    is_free boolean DEFAULT false NOT NULL,
    language_id integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: resource_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resource_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resource_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_translations (
    id integer NOT NULL,
    resource_id integer NOT NULL,
    locale text NOT NULL,
    title text NOT NULL,
    alternative_title text,
    description text,
    personal_note text,
    reason_found text,
    seo text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: resource_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resource_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resources (
    id integer NOT NULL,
    slug text NOT NULL,
    public_id character varying(6) NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    "order" integer NOT NULL,
    type text NOT NULL,
    language_id integer,
    authors text,
    organizations text,
    published_date_iso date,
    found_date_iso date,
    consumption_state text,
    rating text,
    editorial_state text,
    visibility text,
    type_details text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    featured boolean DEFAULT false NOT NULL,
    featured_order integer,
    popularity_kind text,
    popularity_rank double precision,
    popularity_refreshed_at timestamp without time zone,
    popularity_value bigint
);


--
-- Name: resources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resume_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resume_languages (
    id integer NOT NULL,
    resume_id integer NOT NULL,
    language_id integer NOT NULL,
    proficiency text,
    "order" integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: resume_languages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resume_languages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resume_selected_case; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resume_selected_case (
    resume_id integer NOT NULL,
    case_study_id integer NOT NULL,
    "order" integer
);


--
-- Name: resume_skill_technology; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resume_skill_technology (
    resume_skill_id integer NOT NULL,
    technology_id integer NOT NULL
);


--
-- Name: resume_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resume_skills (
    id integer NOT NULL,
    resume_id integer NOT NULL,
    "order" integer,
    topic_id integer NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: resume_skills_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resume_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resume_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resume_translations (
    id integer NOT NULL,
    resume_id integer NOT NULL,
    locale text NOT NULL,
    summary text,
    leadership text,
    education text,
    certificates text,
    certifications text,
    publications text,
    recommendations text,
    technical_productions text,
    events text,
    awards text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: resume_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resume_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resumes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resumes (
    id integer NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    hidden boolean DEFAULT false NOT NULL
);


--
-- Name: resumes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resumes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resumes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: site_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.site_settings (
    id integer NOT NULL,
    short_name text,
    portfolio_url text,
    maintenance_enabled boolean DEFAULT false NOT NULL,
    contact_email text,
    contact_available boolean DEFAULT false NOT NULL,
    source_repository_url text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: site_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.site_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: site_settings_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.site_settings_translations (
    id integer NOT NULL,
    site_settings_id integer NOT NULL,
    locale text NOT NULL,
    copyright_template text,
    maintenance_eyebrow text,
    maintenance_title text,
    maintenance_description text,
    seo text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: site_settings_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.site_settings_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_settings_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: snippet_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.snippet_files (
    id integer NOT NULL,
    snippet_id integer NOT NULL,
    path text NOT NULL,
    language text,
    content text NOT NULL,
    "order" integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: snippet_files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.snippet_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.snippet_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: snippet_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.snippet_translations (
    id integer NOT NULL,
    snippet_id integer NOT NULL,
    locale text NOT NULL,
    title text NOT NULL,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: snippet_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.snippet_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.snippet_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: snippets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.snippets (
    id integer NOT NULL,
    slug text NOT NULL,
    public_id character varying(6) NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    show_history boolean DEFAULT false NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    published_at date
);


--
-- Name: snippets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.snippets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.snippets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: technologies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.technologies (
    id integer NOT NULL,
    slug text NOT NULL,
    public_id character varying(6) NOT NULL,
    "order" integer NOT NULL,
    code text,
    logo text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    hidden boolean DEFAULT false NOT NULL
);


--
-- Name: technologies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.technologies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.technologies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: technology_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.technology_translations (
    id integer NOT NULL,
    technology_id integer NOT NULL,
    locale text NOT NULL,
    name text NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: technology_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.technology_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.technology_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topic_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topic_translations (
    id integer NOT NULL,
    topic_id integer NOT NULL,
    locale text NOT NULL,
    name text NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: topic_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.topic_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topic_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topicables; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topicables (
    id integer NOT NULL,
    topic_id integer NOT NULL,
    topicable_type text NOT NULL,
    topicable_id integer NOT NULL,
    role text
);


--
-- Name: topicables_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.topicables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topicables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topics (
    id integer NOT NULL,
    slug text NOT NULL,
    public_id character varying(6) NOT NULL,
    "order" integer NOT NULL,
    kind text DEFAULT 'topic'::text NOT NULL,
    parent_id integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    hidden boolean DEFAULT false NOT NULL
);


--
-- Name: topics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.topics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: writing_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.writing_translations (
    id integer NOT NULL,
    writing_id integer NOT NULL,
    locale text NOT NULL,
    title text NOT NULL,
    excerpt text,
    reading_time text,
    body text,
    seo text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: writing_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.writing_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.writing_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: writings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.writings (
    id integer NOT NULL,
    slug text NOT NULL,
    public_id character varying(6) NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    date_iso timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    show_history boolean DEFAULT false NOT NULL,
    type text NOT NULL
);


--
-- Name: writings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.writings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.writings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: audit_log PK_audit_log; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT "PK_audit_log" PRIMARY KEY (id);


--
-- Name: audit_requests PK_audit_requests; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_requests
    ADD CONSTRAINT "PK_audit_requests" PRIMARY KEY (request_id);


--
-- Name: case_studies PK_case_studies; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.case_studies
    ADD CONSTRAINT "PK_case_studies" PRIMARY KEY (id);


--
-- Name: case_study_technology PK_case_study_technology; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.case_study_technology
    ADD CONSTRAINT "PK_case_study_technology" PRIMARY KEY (case_study_id, technology_id);


--
-- Name: case_study_translations PK_case_study_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.case_study_translations
    ADD CONSTRAINT "PK_case_study_translations" PRIMARY KEY (id);


--
-- Name: contact_profiles PK_contact_profiles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_profiles
    ADD CONSTRAINT "PK_contact_profiles" PRIMARY KEY (id);


--
-- Name: content_relations PK_content_relations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_relations
    ADD CONSTRAINT "PK_content_relations" PRIMARY KEY (id);


--
-- Name: content_revisions PK_content_revisions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_revisions
    ADD CONSTRAINT "PK_content_revisions" PRIMARY KEY (id);


--
-- Name: credit_entries PK_credit_entries; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_entries
    ADD CONSTRAINT "PK_credit_entries" PRIMARY KEY (id);


--
-- Name: credit_entry_translations PK_credit_entry_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_entry_translations
    ADD CONSTRAINT "PK_credit_entry_translations" PRIMARY KEY (id);


--
-- Name: experiment_technology PK_experiment_technology; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiment_technology
    ADD CONSTRAINT "PK_experiment_technology" PRIMARY KEY (experiment_id, technology_id);


--
-- Name: experiment_translations PK_experiment_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiment_translations
    ADD CONSTRAINT "PK_experiment_translations" PRIMARY KEY (id);


--
-- Name: experiments PK_experiments; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiments
    ADD CONSTRAINT "PK_experiments" PRIMARY KEY (id);


--
-- Name: language_translations PK_language_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.language_translations
    ADD CONSTRAINT "PK_language_translations" PRIMARY KEY (id);


--
-- Name: languages PK_languages; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT "PK_languages" PRIMARY KEY (id);


--
-- Name: nav_item_translations PK_nav_item_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nav_item_translations
    ADD CONSTRAINT "PK_nav_item_translations" PRIMARY KEY (id);


--
-- Name: nav_items PK_nav_items; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nav_items
    ADD CONSTRAINT "PK_nav_items" PRIMARY KEY (id);


--
-- Name: page_featured_case PK_page_featured_case; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_featured_case
    ADD CONSTRAINT "PK_page_featured_case" PRIMARY KEY (page_id, case_study_id);


--
-- Name: page_featured_project PK_page_featured_project; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_featured_project
    ADD CONSTRAINT "PK_page_featured_project" PRIMARY KEY (page_id, project_id);


--
-- Name: page_featured_writing PK_page_featured_writing; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_featured_writing
    ADD CONSTRAINT "PK_page_featured_writing" PRIMARY KEY (page_id, writing_id);


--
-- Name: page_translations PK_page_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_translations
    ADD CONSTRAINT "PK_page_translations" PRIMARY KEY (id);


--
-- Name: pages PK_pages; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pages
    ADD CONSTRAINT "PK_pages" PRIMARY KEY (id);


--
-- Name: profile_translations PK_profile_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_translations
    ADD CONSTRAINT "PK_profile_translations" PRIMARY KEY (id);


--
-- Name: profiles PK_profiles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT "PK_profiles" PRIMARY KEY (id);


--
-- Name: project_technology PK_project_technology; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_technology
    ADD CONSTRAINT "PK_project_technology" PRIMARY KEY (project_id, technology_id);


--
-- Name: project_translations PK_project_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_translations
    ADD CONSTRAINT "PK_project_translations" PRIMARY KEY (id);


--
-- Name: projects PK_projects; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT "PK_projects" PRIMARY KEY (id);


--
-- Name: reference_collection_item PK_reference_collection_item; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reference_collection_item
    ADD CONSTRAINT "PK_reference_collection_item" PRIMARY KEY (reference_collection_id, resource_id);


--
-- Name: reference_collection_translations PK_reference_collection_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reference_collection_translations
    ADD CONSTRAINT "PK_reference_collection_translations" PRIMARY KEY (id);


--
-- Name: reference_collections PK_reference_collections; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reference_collections
    ADD CONSTRAINT "PK_reference_collections" PRIMARY KEY (id);


--
-- Name: relation_types PK_relation_types; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.relation_types
    ADD CONSTRAINT "PK_relation_types" PRIMARY KEY (id);


--
-- Name: resource_identifiers PK_resource_identifiers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_identifiers
    ADD CONSTRAINT "PK_resource_identifiers" PRIMARY KEY (id);


--
-- Name: resource_links PK_resource_links; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_links
    ADD CONSTRAINT "PK_resource_links" PRIMARY KEY (id);


--
-- Name: resource_translations PK_resource_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_translations
    ADD CONSTRAINT "PK_resource_translations" PRIMARY KEY (id);


--
-- Name: resources PK_resources; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT "PK_resources" PRIMARY KEY (id);


--
-- Name: resume_languages PK_resume_languages; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_languages
    ADD CONSTRAINT "PK_resume_languages" PRIMARY KEY (id);


--
-- Name: resume_selected_case PK_resume_selected_case; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_selected_case
    ADD CONSTRAINT "PK_resume_selected_case" PRIMARY KEY (resume_id, case_study_id);


--
-- Name: resume_skill_technology PK_resume_skill_technology; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_skill_technology
    ADD CONSTRAINT "PK_resume_skill_technology" PRIMARY KEY (resume_skill_id, technology_id);


--
-- Name: resume_skills PK_resume_skills; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_skills
    ADD CONSTRAINT "PK_resume_skills" PRIMARY KEY (id);


--
-- Name: resume_translations PK_resume_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_translations
    ADD CONSTRAINT "PK_resume_translations" PRIMARY KEY (id);


--
-- Name: resumes PK_resumes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT "PK_resumes" PRIMARY KEY (id);


--
-- Name: site_settings PK_site_settings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.site_settings
    ADD CONSTRAINT "PK_site_settings" PRIMARY KEY (id);


--
-- Name: site_settings_translations PK_site_settings_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.site_settings_translations
    ADD CONSTRAINT "PK_site_settings_translations" PRIMARY KEY (id);


--
-- Name: snippet_files PK_snippet_files; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snippet_files
    ADD CONSTRAINT "PK_snippet_files" PRIMARY KEY (id);


--
-- Name: snippet_translations PK_snippet_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snippet_translations
    ADD CONSTRAINT "PK_snippet_translations" PRIMARY KEY (id);


--
-- Name: snippets PK_snippets; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snippets
    ADD CONSTRAINT "PK_snippets" PRIMARY KEY (id);


--
-- Name: technologies PK_technologies; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.technologies
    ADD CONSTRAINT "PK_technologies" PRIMARY KEY (id);


--
-- Name: technology_translations PK_technology_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.technology_translations
    ADD CONSTRAINT "PK_technology_translations" PRIMARY KEY (id);


--
-- Name: topic_translations PK_topic_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic_translations
    ADD CONSTRAINT "PK_topic_translations" PRIMARY KEY (id);


--
-- Name: topicables PK_topicables; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topicables
    ADD CONSTRAINT "PK_topicables" PRIMARY KEY (id);


--
-- Name: topics PK_topics; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT "PK_topics" PRIMARY KEY (id);


--
-- Name: writing_translations PK_writing_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.writing_translations
    ADD CONSTRAINT "PK_writing_translations" PRIMARY KEY (id);


--
-- Name: writings PK_writings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.writings
    ADD CONSTRAINT "PK_writings" PRIMARY KEY (id);


--
-- Name: audit_log_auditable_type_auditable_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_auditable_type_auditable_id_index ON public.audit_log USING btree (auditable_type, auditable_id);


--
-- Name: case_studies_public_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX case_studies_public_id_unique ON public.case_studies USING btree (public_id);


--
-- Name: case_studies_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX case_studies_slug_unique ON public.case_studies USING btree (slug);


--
-- Name: case_study_translations_case_study_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX case_study_translations_case_study_id_locale_unique ON public.case_study_translations USING btree (case_study_id, locale);


--
-- Name: content_relations_object_type_object_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_relations_object_type_object_id_index ON public.content_relations USING btree (object_type, object_id);


--
-- Name: content_relations_subject_type_subject_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_relations_subject_type_subject_id_index ON public.content_relations USING btree (subject_type, subject_id);


--
-- Name: credit_entry_translations_credit_entry_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX credit_entry_translations_credit_entry_id_locale_unique ON public.credit_entry_translations USING btree (credit_entry_id, locale);


--
-- Name: experiment_translations_experiment_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX experiment_translations_experiment_id_locale_unique ON public.experiment_translations USING btree (experiment_id, locale);


--
-- Name: experiments_public_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX experiments_public_id_unique ON public.experiments USING btree (public_id);


--
-- Name: experiments_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX experiments_slug_unique ON public.experiments USING btree (slug);


--
-- Name: language_translations_language_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX language_translations_language_id_locale_unique ON public.language_translations USING btree (language_id, locale);


--
-- Name: languages_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX languages_slug_unique ON public.languages USING btree (slug);


--
-- Name: nav_item_translations_nav_item_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX nav_item_translations_nav_item_id_locale_unique ON public.nav_item_translations USING btree (nav_item_id, locale);


--
-- Name: page_translations_page_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX page_translations_page_id_locale_unique ON public.page_translations USING btree (page_id, locale);


--
-- Name: pages_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX pages_slug_unique ON public.pages USING btree (slug);


--
-- Name: profile_translations_profile_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX profile_translations_profile_id_locale_unique ON public.profile_translations USING btree (profile_id, locale);


--
-- Name: project_translations_project_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX project_translations_project_id_locale_unique ON public.project_translations USING btree (project_id, locale);


--
-- Name: projects_public_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX projects_public_id_unique ON public.projects USING btree (public_id);


--
-- Name: projects_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX projects_slug_unique ON public.projects USING btree (slug);


--
-- Name: reference_collection_translations_reference_collection_id_local; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX reference_collection_translations_reference_collection_id_local ON public.reference_collection_translations USING btree (reference_collection_id, locale);


--
-- Name: reference_collections_public_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX reference_collections_public_id_unique ON public.reference_collections USING btree (public_id);


--
-- Name: reference_collections_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX reference_collections_slug_unique ON public.reference_collections USING btree (slug);


--
-- Name: relation_types_key_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX relation_types_key_unique ON public.relation_types USING btree (key);


--
-- Name: resource_translations_resource_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX resource_translations_resource_id_locale_unique ON public.resource_translations USING btree (resource_id, locale);


--
-- Name: resources_public_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX resources_public_id_unique ON public.resources USING btree (public_id);


--
-- Name: resources_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX resources_slug_unique ON public.resources USING btree (slug);


--
-- Name: resume_translations_resume_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX resume_translations_resume_id_locale_unique ON public.resume_translations USING btree (resume_id, locale);


--
-- Name: site_settings_translations_site_settings_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX site_settings_translations_site_settings_id_locale_unique ON public.site_settings_translations USING btree (site_settings_id, locale);


--
-- Name: snippet_translations_snippet_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX snippet_translations_snippet_id_locale_unique ON public.snippet_translations USING btree (snippet_id, locale);


--
-- Name: snippets_public_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX snippets_public_id_unique ON public.snippets USING btree (public_id);


--
-- Name: snippets_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX snippets_slug_unique ON public.snippets USING btree (slug);


--
-- Name: technologies_public_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX technologies_public_id_unique ON public.technologies USING btree (public_id);


--
-- Name: technologies_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX technologies_slug_unique ON public.technologies USING btree (slug);


--
-- Name: technology_translations_technology_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX technology_translations_technology_id_locale_unique ON public.technology_translations USING btree (technology_id, locale);


--
-- Name: topic_translations_topic_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX topic_translations_topic_id_locale_unique ON public.topic_translations USING btree (topic_id, locale);


--
-- Name: topicables_topic_id_topicable_type_topicable_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX topicables_topic_id_topicable_type_topicable_id_unique ON public.topicables USING btree (topic_id, topicable_type, topicable_id);


--
-- Name: topicables_topicable_type_topicable_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX topicables_topicable_type_topicable_id_index ON public.topicables USING btree (topicable_type, topicable_id);


--
-- Name: topics_parent_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX topics_parent_id_index ON public.topics USING btree (parent_id);


--
-- Name: topics_public_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX topics_public_id_unique ON public.topics USING btree (public_id);


--
-- Name: topics_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX topics_slug_unique ON public.topics USING btree (slug);


--
-- Name: writing_translations_writing_id_locale_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX writing_translations_writing_id_locale_unique ON public.writing_translations USING btree (writing_id, locale);


--
-- Name: writings_public_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX writings_public_id_unique ON public.writings USING btree (public_id);


--
-- Name: writings_slug_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX writings_slug_unique ON public.writings USING btree (slug);


--
-- Name: case_study_technology FK_case_study_technology_case_studies_case_study_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.case_study_technology
    ADD CONSTRAINT "FK_case_study_technology_case_studies_case_study_id" FOREIGN KEY (case_study_id) REFERENCES public.case_studies(id) ON DELETE CASCADE;


--
-- Name: case_study_technology FK_case_study_technology_technologies_technology_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.case_study_technology
    ADD CONSTRAINT "FK_case_study_technology_technologies_technology_id" FOREIGN KEY (technology_id) REFERENCES public.technologies(id) ON DELETE CASCADE;


--
-- Name: case_study_translations FK_case_study_translations_case_studies_case_study_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.case_study_translations
    ADD CONSTRAINT "FK_case_study_translations_case_studies_case_study_id" FOREIGN KEY (case_study_id) REFERENCES public.case_studies(id) ON DELETE CASCADE;


--
-- Name: contact_profiles FK_contact_profiles_site_settings_site_settings_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_profiles
    ADD CONSTRAINT "FK_contact_profiles_site_settings_site_settings_id" FOREIGN KEY (site_settings_id) REFERENCES public.site_settings(id) ON DELETE CASCADE;


--
-- Name: content_relations FK_content_relations_relation_types_relation_type_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_relations
    ADD CONSTRAINT "FK_content_relations_relation_types_relation_type_id" FOREIGN KEY (relation_type_id) REFERENCES public.relation_types(id) ON DELETE CASCADE;


--
-- Name: credit_entry_translations FK_credit_entry_translations_credit_entries_credit_entry_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_entry_translations
    ADD CONSTRAINT "FK_credit_entry_translations_credit_entries_credit_entry_id" FOREIGN KEY (credit_entry_id) REFERENCES public.credit_entries(id) ON DELETE CASCADE;


--
-- Name: experiment_technology FK_experiment_technology_experiments_experiment_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiment_technology
    ADD CONSTRAINT "FK_experiment_technology_experiments_experiment_id" FOREIGN KEY (experiment_id) REFERENCES public.experiments(id) ON DELETE CASCADE;


--
-- Name: experiment_technology FK_experiment_technology_technologies_technology_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiment_technology
    ADD CONSTRAINT "FK_experiment_technology_technologies_technology_id" FOREIGN KEY (technology_id) REFERENCES public.technologies(id) ON DELETE CASCADE;


--
-- Name: experiment_translations FK_experiment_translations_experiments_experiment_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiment_translations
    ADD CONSTRAINT "FK_experiment_translations_experiments_experiment_id" FOREIGN KEY (experiment_id) REFERENCES public.experiments(id) ON DELETE CASCADE;


--
-- Name: language_translations FK_language_translations_languages_language_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.language_translations
    ADD CONSTRAINT "FK_language_translations_languages_language_id" FOREIGN KEY (language_id) REFERENCES public.languages(id) ON DELETE CASCADE;


--
-- Name: nav_item_translations FK_nav_item_translations_nav_items_nav_item_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nav_item_translations
    ADD CONSTRAINT "FK_nav_item_translations_nav_items_nav_item_id" FOREIGN KEY (nav_item_id) REFERENCES public.nav_items(id) ON DELETE CASCADE;


--
-- Name: nav_items FK_nav_items_nav_items_parent_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nav_items
    ADD CONSTRAINT "FK_nav_items_nav_items_parent_id" FOREIGN KEY (parent_id) REFERENCES public.nav_items(id) ON DELETE SET NULL;


--
-- Name: page_featured_case FK_page_featured_case_case_studies_case_study_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_featured_case
    ADD CONSTRAINT "FK_page_featured_case_case_studies_case_study_id" FOREIGN KEY (case_study_id) REFERENCES public.case_studies(id) ON DELETE CASCADE;


--
-- Name: page_featured_case FK_page_featured_case_pages_page_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_featured_case
    ADD CONSTRAINT "FK_page_featured_case_pages_page_id" FOREIGN KEY (page_id) REFERENCES public.pages(id) ON DELETE CASCADE;


--
-- Name: page_featured_project FK_page_featured_project_pages_page_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_featured_project
    ADD CONSTRAINT "FK_page_featured_project_pages_page_id" FOREIGN KEY (page_id) REFERENCES public.pages(id) ON DELETE CASCADE;


--
-- Name: page_featured_project FK_page_featured_project_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_featured_project
    ADD CONSTRAINT "FK_page_featured_project_projects_project_id" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: page_featured_writing FK_page_featured_writing_pages_page_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_featured_writing
    ADD CONSTRAINT "FK_page_featured_writing_pages_page_id" FOREIGN KEY (page_id) REFERENCES public.pages(id) ON DELETE CASCADE;


--
-- Name: page_featured_writing FK_page_featured_writing_writings_writing_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_featured_writing
    ADD CONSTRAINT "FK_page_featured_writing_writings_writing_id" FOREIGN KEY (writing_id) REFERENCES public.writings(id) ON DELETE CASCADE;


--
-- Name: page_translations FK_page_translations_pages_page_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_translations
    ADD CONSTRAINT "FK_page_translations_pages_page_id" FOREIGN KEY (page_id) REFERENCES public.pages(id) ON DELETE CASCADE;


--
-- Name: profile_translations FK_profile_translations_profiles_profile_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_translations
    ADD CONSTRAINT "FK_profile_translations_profiles_profile_id" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE;


--
-- Name: project_technology FK_project_technology_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_technology
    ADD CONSTRAINT "FK_project_technology_projects_project_id" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: project_technology FK_project_technology_technologies_technology_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_technology
    ADD CONSTRAINT "FK_project_technology_technologies_technology_id" FOREIGN KEY (technology_id) REFERENCES public.technologies(id) ON DELETE CASCADE;


--
-- Name: project_translations FK_project_translations_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_translations
    ADD CONSTRAINT "FK_project_translations_projects_project_id" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: reference_collection_item FK_reference_collection_item_reference_collections_reference_c~; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reference_collection_item
    ADD CONSTRAINT "FK_reference_collection_item_reference_collections_reference_c~" FOREIGN KEY (reference_collection_id) REFERENCES public.reference_collections(id) ON DELETE CASCADE;


--
-- Name: reference_collection_item FK_reference_collection_item_resources_resource_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reference_collection_item
    ADD CONSTRAINT "FK_reference_collection_item_resources_resource_id" FOREIGN KEY (resource_id) REFERENCES public.resources(id) ON DELETE CASCADE;


--
-- Name: reference_collection_translations FK_reference_collection_translations_reference_collections_ref~; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reference_collection_translations
    ADD CONSTRAINT "FK_reference_collection_translations_reference_collections_ref~" FOREIGN KEY (reference_collection_id) REFERENCES public.reference_collections(id) ON DELETE CASCADE;


--
-- Name: resource_identifiers FK_resource_identifiers_resources_resource_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_identifiers
    ADD CONSTRAINT "FK_resource_identifiers_resources_resource_id" FOREIGN KEY (resource_id) REFERENCES public.resources(id) ON DELETE CASCADE;


--
-- Name: resource_links FK_resource_links_languages_language_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_links
    ADD CONSTRAINT "FK_resource_links_languages_language_id" FOREIGN KEY (language_id) REFERENCES public.languages(id) ON DELETE SET NULL;


--
-- Name: resource_links FK_resource_links_resources_resource_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_links
    ADD CONSTRAINT "FK_resource_links_resources_resource_id" FOREIGN KEY (resource_id) REFERENCES public.resources(id) ON DELETE CASCADE;


--
-- Name: resource_translations FK_resource_translations_resources_resource_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_translations
    ADD CONSTRAINT "FK_resource_translations_resources_resource_id" FOREIGN KEY (resource_id) REFERENCES public.resources(id) ON DELETE CASCADE;


--
-- Name: resources FK_resources_languages_language_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT "FK_resources_languages_language_id" FOREIGN KEY (language_id) REFERENCES public.languages(id) ON DELETE SET NULL;


--
-- Name: resume_languages FK_resume_languages_languages_language_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_languages
    ADD CONSTRAINT "FK_resume_languages_languages_language_id" FOREIGN KEY (language_id) REFERENCES public.languages(id) ON DELETE CASCADE;


--
-- Name: resume_languages FK_resume_languages_resumes_resume_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_languages
    ADD CONSTRAINT "FK_resume_languages_resumes_resume_id" FOREIGN KEY (resume_id) REFERENCES public.resumes(id) ON DELETE CASCADE;


--
-- Name: resume_selected_case FK_resume_selected_case_case_studies_case_study_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_selected_case
    ADD CONSTRAINT "FK_resume_selected_case_case_studies_case_study_id" FOREIGN KEY (case_study_id) REFERENCES public.case_studies(id) ON DELETE CASCADE;


--
-- Name: resume_selected_case FK_resume_selected_case_resumes_resume_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_selected_case
    ADD CONSTRAINT "FK_resume_selected_case_resumes_resume_id" FOREIGN KEY (resume_id) REFERENCES public.resumes(id) ON DELETE CASCADE;


--
-- Name: resume_skill_technology FK_resume_skill_technology_resume_skills_resume_skill_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_skill_technology
    ADD CONSTRAINT "FK_resume_skill_technology_resume_skills_resume_skill_id" FOREIGN KEY (resume_skill_id) REFERENCES public.resume_skills(id) ON DELETE CASCADE;


--
-- Name: resume_skill_technology FK_resume_skill_technology_technologies_technology_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_skill_technology
    ADD CONSTRAINT "FK_resume_skill_technology_technologies_technology_id" FOREIGN KEY (technology_id) REFERENCES public.technologies(id) ON DELETE CASCADE;


--
-- Name: resume_skills FK_resume_skills_resumes_resume_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_skills
    ADD CONSTRAINT "FK_resume_skills_resumes_resume_id" FOREIGN KEY (resume_id) REFERENCES public.resumes(id) ON DELETE CASCADE;


--
-- Name: resume_skills FK_resume_skills_topics_topic_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_skills
    ADD CONSTRAINT "FK_resume_skills_topics_topic_id" FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;


--
-- Name: resume_translations FK_resume_translations_resumes_resume_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_translations
    ADD CONSTRAINT "FK_resume_translations_resumes_resume_id" FOREIGN KEY (resume_id) REFERENCES public.resumes(id) ON DELETE CASCADE;


--
-- Name: site_settings_translations FK_site_settings_translations_site_settings_site_settings_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.site_settings_translations
    ADD CONSTRAINT "FK_site_settings_translations_site_settings_site_settings_id" FOREIGN KEY (site_settings_id) REFERENCES public.site_settings(id) ON DELETE CASCADE;


--
-- Name: snippet_files FK_snippet_files_snippets_snippet_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snippet_files
    ADD CONSTRAINT "FK_snippet_files_snippets_snippet_id" FOREIGN KEY (snippet_id) REFERENCES public.snippets(id) ON DELETE CASCADE;


--
-- Name: snippet_translations FK_snippet_translations_snippets_snippet_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snippet_translations
    ADD CONSTRAINT "FK_snippet_translations_snippets_snippet_id" FOREIGN KEY (snippet_id) REFERENCES public.snippets(id) ON DELETE CASCADE;


--
-- Name: technology_translations FK_technology_translations_technologies_technology_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.technology_translations
    ADD CONSTRAINT "FK_technology_translations_technologies_technology_id" FOREIGN KEY (technology_id) REFERENCES public.technologies(id) ON DELETE CASCADE;


--
-- Name: topic_translations FK_topic_translations_topics_topic_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic_translations
    ADD CONSTRAINT "FK_topic_translations_topics_topic_id" FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;


--
-- Name: topicables FK_topicables_topics_topic_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topicables
    ADD CONSTRAINT "FK_topicables_topics_topic_id" FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;


--
-- Name: topics FK_topics_topics_parent_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT "FK_topics_topics_parent_id" FOREIGN KEY (parent_id) REFERENCES public.topics(id) ON DELETE SET NULL;


--
-- Name: writing_translations FK_writing_translations_writings_writing_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.writing_translations
    ADD CONSTRAINT "FK_writing_translations_writings_writing_id" FOREIGN KEY (writing_id) REFERENCES public.writings(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

