import type { SxProps, Theme } from '@mui/material/styles';

export const typographyVariants3: Record<string, SxProps<Theme>> = {
  caseLinkReadMore: {
    mt: 2,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    fontWeight: 600,
  },
  referenceCardTitle: { fontSize: 'var(--site-text-xl)', transition: 'color .2s' },
  referenceCardDescription: { fontSize: 'var(--site-text-body)', maxWidth: '48ch' },
  contentFeedHeader: {
    maxWidth: 'var(--site-lede-max)',
    marginLeft: 'auto',
    marginRight: 'auto',
    mt: 'var(--site-space-3)',
    textAlign: 'center',
    hyphens: 'auto',
  },
  contentFeedStatus: { textAlign: 'center' },
  feedCard: {
    margin: 0,
    color: 'var(--site-text-primary)',
    fontSize: 'var(--site-text-xl)',
    fontWeight: 'var(--site-weight-bold)',
    letterSpacing: 'var(--site-letter-heading)',
    lineHeight: 'var(--site-leading-tight)',
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    transition: 'color .2s',
  },
  feedCard2: {
    mt: 'var(--site-space-2)',
    color: 'var(--site-text-primary)',
    fontSize: 'var(--site-text-body)',
    lineHeight: 'var(--site-leading-relaxed)',
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 3,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  metricItem: { fontWeight: 700 },
  explorationSection: {
    maxWidth: 'var(--site-lede-max)',
    marginLeft: 'auto',
    marginRight: 'auto',
    mt: 'var(--site-space-3)',
    textAlign: 'center',
    hyphens: 'auto',
  },
  connectionsSection: {
    margin: 0,
    fontSize: 'var(--site-text-2xl)',
    fontWeight: 'var(--site-weight-bold)',
    letterSpacing: 'var(--site-letter-heading)',
    lineHeight: 'var(--site-leading-tight)',
  },
  connectionGroup: {
    marginBottom: 'var(--site-space-2)',
    color: 'var(--site-text-secondary)',
    fontSize: 'var(--site-text-sm)',
    fontWeight: 'var(--site-weight-semibold)',
    textTransform: 'capitalize',
  },
  detailHeader: { display: 'block' },
  detailHeader2: { mt: 1.5, fontSize: 'var(--site-text-3xl)' },
  detailHeader3: { mt: 2.5, maxWidth: '62ch', fontSize: '1.0625rem', lineHeight: 1.65 },
  detailHeader4: { mt: 2, fontSize: '.8125rem' },
  pageHeader: { display: 'block', mb: 1.5 },
  pageHeader2: { fontSize: 'var(--site-text-3xl)' },
  pageHeader3: { maxWidth: '60ch', mt: 2, fontSize: '1rem' },
  sourcePreviewListMetadataItem: {
    minWidth: 0,
    maxWidth: '100%',
    color: 'var(--site-text-secondary)',
    fontSize: 'var(--site-text-xs)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  caseIllustration: {
    position: 'absolute',
    zIndex: 1,
    right: '1rem',
    bottom: '0.75rem',
    color: 'text.disabled',
  },
  breadcrumbTrailItem: { px: 'var(--site-action-px)', py: 'var(--site-action-py)' },
  revealDialogContentView: { mb: 2.5 },
  caseLinkTitleCompact: { mt: 1.5, fontSize: '1.25rem', transition: 'color .2s' },
  caseLinkTitleFull: { mt: 1.5, fontSize: '1.5rem', transition: 'color .2s' },
  explorationTitle: { mt: 'var(--site-space-2)' },
  sourcePreviewTitleFeed: {
    margin: 0,
    color: 'var(--site-text-primary)',
    fontSize: 'var(--site-text-sm)',
    fontWeight: 'var(--site-weight-bold)',
    lineHeight: 'var(--site-leading-tight)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};
