import type { SxProps, Theme } from '@mui/material/styles';

export const typographyVariants1: Record<string, SxProps<Theme>> = {
  timelineRow: { fontSize: '.8125rem' },
  timelineRow2: { fontWeight: 650 },
  timelineRow3: { mt: 0.35, fontSize: '.875rem' },
  timelineRow4: { mt: 1, maxWidth: '68ch', fontSize: '.9rem' },
  emptyState: {
    maxWidth: '48ch',
    fontFamily: 'var(--site-font-mono)',
    fontSize: 'var(--site-text-sm)',
    whiteSpace: 'normal',
  },
  sectionHeadingGrid: { fontSize: { xs: '1.75rem', md: '2rem' }, maxWidth: '28ch' },
  sectionHeadingGrid2: {
    gridColumn: '1 / -1',
    gridRow: 2,
    maxWidth: 'var(--site-lede-max)',
    marginLeft: 'auto',
    marginRight: 'auto',
    textAlign: 'center',
  },
  sectionHeadingContent: { display: 'block', mb: 1.25 },
  maintenanceTitle: { mt: 2, fontSize: { xs: '2.5rem', sm: '3rem' } },
  maintenanceDescription: { mt: 2.5, maxWidth: '34rem' },
  maintenanceSignature: { mt: 6 },
  creditEntryItem: { fontWeight: 700 },
  aboutIntroText: { fontSize: { xs: '1.5rem', md: '1.75rem' }, maxWidth: '30ch' },
  aboutIntroText2: { mt: 3, maxWidth: '62ch' },
  aboutIntroText3: { mt: 2.5, maxWidth: '62ch' },
  aboutEditorialLabel: {
    display: 'block',
    color: 'var(--site-text-secondary)',
    fontFamily: 'var(--site-font-action)',
    fontSize: 'var(--site-text-xs)',
    letterSpacing: 'var(--site-letter-label)',
    textTransform: 'uppercase',
  },
  aboutEditorialSectionTitle: {
    margin: 0,
    fontFamily: 'var(--site-font-family)',
    fontSize: 'var(--site-text-2xl)',
    lineHeight: 'var(--site-leading-tight)',
  },
  aboutTimelinePeriod: {
    paddingTop: 'var(--site-space-1)',
    fontFamily: 'var(--site-font-mono)',
    fontSize: 'var(--site-text-sm)',
    lineHeight: 'var(--site-leading-normal)',
  },
  aboutTimelineTitle: {
    margin: 0,
    fontFamily: 'var(--site-font-family)',
    fontSize: 'var(--site-text-lg)',
    lineHeight: 'var(--site-leading-tight)',
  },
  richTextPlainParagraph: {
    margin: 0,
    color: 'text.primary',
    fontSize: 'var(--site-text-body)',
    lineHeight: 'var(--site-leading-relaxed)',
    textAlign: 'justify',
    hyphens: 'auto',
  },
  profileMilestones: { display: 'block', mb: 2 },
  aboutStory: { display: 'block' },
  aboutStory2: { mt: 1, fontSize: { xs: '1.5rem', md: '1.75rem' } },
  profileTrajectory: { display: 'block', mb: 2 },
  profileSummary: { mt: 1.5, fontSize: '1.25rem' },
  profileSummary2: { mt: 0.75, fontSize: '.875rem' },
  profileSummarySection: { mt: 1, fontSize: '.875rem' },
  profileBirthDetails: { mt: 0.25, fontSize: '.875rem' },
  collectionReferenceItem: { mt: 1.5, fontStyle: 'italic', maxWidth: '52ch' },
  followSectionTitle: { mt: 1, mb: 3 },
  followFutureTitle: { mt: 1, mb: 3 },
  snippetFile: {
    px: 2,
    py: 1.5,
    borderBottom: 1,
    borderColor: 'divider',
    fontFamily: 'var(--site-font-mono)',
  },
  licenseSection: { mb: 1.5 },
  licenseSection2: { lineHeight: 1.7 },
};
