import type { SxProps, Theme } from '@mui/material/styles';

export const typographyVariants1: Record<string, SxProps<Theme>> = {
  timelineRow: { fontSize: '.8125rem' },
  timelineRow2: { fontWeight: 650 },
  timelineRow3: { mt: 0.35, fontSize: '.875rem' },
  timelineRow4: { mt: 1, maxWidth: '68ch', fontSize: '.9rem' },
  emptyState: {
    maxWidth: '48ch',
    fontFamily: 'var(--site-font-mono)',
    fontSize: 'var(--site-text-sm)',
    whiteSpace: 'normal',
  },
  sectionHeadingGrid: { fontSize: { xs: '1.75rem', md: '2rem' }, maxWidth: '28ch' },
  sectionHeadingGrid2: {
    gridColumn: '1 / -1',
    gridRow: 2,
    maxWidth: 'var(--site-lede-max)',
    marginLeft: 'auto',
    marginRight: 'auto',
    textAlign: 'center',
  },
  projectCardSurface: { mt: 1.5, fontSize: '1.25rem', transition: 'color .2s' },
  projectCardSurface2: { mt: 1.25, fontSize: '.9rem', maxWidth: '48ch' },
  projectCardSurface3: { mt: 2, fontSize: '.85rem' },
  projectCardSurface4: { mt: 'auto', pt: 3, color: 'text.secondary', fontSize: '.8rem' },
  projectCardSurface5: {
    mt: 2,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    fontWeight: 600,
  },
  sectionHeadingContent: { display: 'block', mb: 1.25 },
  maintenanceTitle: { mt: 2, fontSize: { xs: '2.5rem', sm: '3rem' } },
  maintenanceDescription: { mt: 2.5, maxWidth: '34rem' },
  maintenanceSignature: { mt: 6 },
  caseCard: {
    mt: 'var(--site-space-1)',
    fontSize: 'var(--site-text-xl)',
    transition: 'color .2s',
  },
  caseCard2: {
    mt: 'var(--site-space-1)',
    maxWidth: '58ch',
    fontSize: 'var(--site-text-body)',
  },
  caseCard3: {
    mt: 'var(--site-space-2)',
    pt: 'var(--site-space-3)',
    color: 'text.secondary',
    fontSize: 'var(--site-text-sm)',
  },
  caseCard4: {
    mt: 'var(--site-space-2)',
    display: 'inline-flex',
    gap: 'var(--site-space-1)',
    alignItems: 'center',
    fontWeight: 'var(--site-weight-semibold)',
  },
  creditEntryItem: { fontWeight: 700 },
  aboutIntroText: { fontSize: { xs: '1.5rem', md: '1.75rem' }, maxWidth: '30ch' },
  aboutIntroText2: { mt: 3, maxWidth: '62ch' },
  aboutIntroText3: { mt: 2.5, maxWidth: '62ch' },
  aboutEditorialLabel: {
    display: 'block',
    color: 'var(--site-text-secondary)',
    fontFamily: 'var(--site-font-action)',
    fontSize: 'var(--site-text-xs)',
    letterSpacing: 'var(--site-letter-label)',
    textTransform: 'uppercase',
  },
  aboutEditorialSectionTitle: {
    margin: 0,
    fontFamily: 'var(--site-font-family)',
    fontSize: 'var(--site-text-2xl)',
    lineHeight: 'var(--site-leading-tight)',
  },
  aboutTimelinePeriod: {
    paddingTop: 'var(--site-space-1)',
    fontFamily: 'var(--site-font-mono)',
    fontSize: 'var(--site-text-sm)',
    lineHeight: 'var(--site-leading-normal)',
  },
  aboutTimelineTitle: {
    margin: 0,
    fontFamily: 'var(--site-font-family)',
    fontSize: 'var(--site-text-lg)',
    lineHeight: 'var(--site-leading-tight)',
  },
  richTextPlainParagraph: {
    margin: 0,
    color: 'text.primary',
    fontSize: 'var(--site-text-body)',
    lineHeight: 'var(--site-leading-relaxed)',
    textAlign: 'justify',
    hyphens: 'auto',
  },
  profileMilestones: { display: 'block', mb: 2 },
  aboutStory: { display: 'block' },
  aboutStory2: { mt: 1, fontSize: { xs: '1.5rem', md: '1.75rem' } },
  profileTrajectory: { display: 'block', mb: 2 },
  profileSummary: { mt: 1.5, fontSize: '1.25rem' },
  profileSummary2: { mt: 0.75, fontSize: '.875rem' },
  profileSummarySection: { mt: 1, fontSize: '.875rem' },
  profileBirthDetails: { mt: 0.25, fontSize: '.875rem' },
  collectionReferenceItem: { mt: 1.5, fontStyle: 'italic', maxWidth: '52ch' },
  followEntryCard: { mt: 1 },
  followSectionTitle: { mt: 1, mb: 3 },
  followFutureTitle: { mt: 1, mb: 3 },
  snippetFile: {
    px: 2,
    py: 1.5,
    borderBottom: 1,
    borderColor: 'divider',
    fontFamily: 'var(--site-font-mono)',
  },
  licenseSection: { mb: 1.5 },
  licenseSection2: { lineHeight: 1.7 },
  editableItemName: { fontWeight: 700 },
  entryDescription: { mt: 0.5 },
  resumeSection: {
    display: 'block',
    color: 'text.primary',
    fontWeight: 700,
    letterSpacing: '0.12em',
  },
  technicalProductionEntries: { gridColumn: { sm: '1 / -1' }, fontStyle: 'italic' },
  highlightItem: { mb: 0.25 },
  recommendationEntry: { fontWeight: 700 },
  recommendationEntry2: { gridColumn: { sm: '1 / -1' }, fontStyle: 'italic' },
  recommendationEntry3: { mt: 1 },
  resumeCase: { mt: 0.75 },
  resumeCase2: { mt: 0.5 },
  credentialEntries: { fontStyle: 'italic' },
  eventEntries: { gridColumn: { sm: '1 / -1' }, fontStyle: 'italic' },
  resumeHeader: { fontWeight: 700, mt: 0.5 },
  resumeHeader2: { mt: 0.5, color: 'text.secondary' },
  resumeHeader3: { mt: 0.5 },
  awardEntries: { gridColumn: { sm: '1 / -1' }, fontStyle: 'italic' },
  trajectoryEntry: { fontWeight: 700 },
  trajectoryEntry2: { gridColumn: { sm: '1 / -1' }, fontStyle: 'italic' },
  educationEntry: { fontWeight: 700 },
  educationEntry2: { fontStyle: 'italic' },
};
