import type { SxProps, Theme } from '@mui/material/styles';

export const typographyVariants2: Record<string, SxProps<Theme>> = {
  referenceLinkLabel: {
    fontSize: 'var(--site-text-body)',
    fontWeight: 'var(--site-weight-medium)',
    lineHeight: 'var(--site-leading-tight)',
    overflowWrap: 'anywhere',
  },
  referenceLinkLabel2: {
    color: 'var(--site-text-secondary)',
    fontSize: 'var(--site-text-xs)',
    lineHeight: 'var(--site-leading-normal)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  factEntry: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--site-space-1)',
    margin: 0,
    color: 'var(--site-text-secondary)',
    fontSize: 'var(--site-text-xs)',
    fontWeight: 'var(--site-weight-medium)',
    letterSpacing: 'var(--site-letter-label)',
    textTransform: 'uppercase',
  },
  factEntry2: {
    margin: 0,
    color: 'var(--site-text-primary)',
    fontSize: 'var(--site-text-body)',
    fontWeight: 'var(--site-weight-medium)',
    lineHeight: 'var(--site-leading-normal)',
    overflowWrap: 'anywhere',
  },
  findingSection: {
    margin: 0,
    fontSize: 'var(--site-text-2xl)',
    fontWeight: 'var(--site-weight-bold)',
    letterSpacing: 'var(--site-letter-heading)',
    lineHeight: 'var(--site-leading-tight)',
  },
  achadoDetailContent: {
    margin: 0,
    color: 'var(--site-text-primary)',
    fontSize: 'var(--site-text-3xl)',
    fontWeight: 'var(--site-weight-bold)',
    letterSpacing: 'var(--site-letter-heading)',
    lineHeight: 'var(--site-leading-tight)',
  },
  achadoDetailContent2: {
    maxWidth: '62ch',
    color: 'var(--site-text-primary)',
    fontSize: 'var(--site-text-lg)',
    lineHeight: 'var(--site-leading-relaxed)',
  },
  achadoDetailContent3: {
    color: 'var(--site-text-secondary)',
    fontSize: 'var(--site-text-sm)',
  },
  achadoDetailContent4: {
    color: 'var(--site-text-secondary)',
    fontSize: 'var(--site-text-sm)',
  },
  achadoDetailContent5: { margin: 0, lineHeight: 'var(--site-leading-relaxed)' },
  achadoDetailContent6: { margin: 0, lineHeight: 'var(--site-leading-relaxed)' },
  selectedProjectsLabel: { display: 'block', mb: 2 },
  projectRow: { fontSize: 'var(--site-text-xl)', fontWeight: 'var(--site-weight-semibold)' },
  experimentRow: { fontWeight: 'var(--site-weight-semibold)', mb: 'var(--site-space-1)' },
  experimentRow2: { maxWidth: '56ch' },
  experimentsSection: { display: 'block', mb: 1.5, scrollMarginTop: '6rem' },
  experimentsSection2: { fontWeight: 600, mb: 3 },
  topicTitle: { fontWeight: 'var(--site-weight-semibold)' },
  caseDetailContent: {
    mt: 6,
    pt: 3,
    borderTop: 1,
    borderColor: 'divider',
    color: 'text.secondary',
    fontSize: '.875rem',
  },
  caseDetailMetric: { display: 'flex', alignItems: 'center', gap: 0.5, mb: 1 },
  projectDetailContent: { display: 'block', mb: 1 },
  projectDetailContent2: { mb: 4 },
  projectOverview: { mt: 1 },
  projectOverview2: { mt: 1 },
  generatedString: { fontFamily: 'var(--site-font-mono)', overflowWrap: 'anywhere' },
  sidebarContentFooter: { textAlign: 'center' },
  sidebarSection: { display: 'block' },
  featuredCaseDetails: { mt: 1.5, fontSize: { xs: '1.5rem', md: '1.75rem' } },
  featuredCaseDetails2: { mt: 1.25, maxWidth: '56ch' },
  featuredCaseFooter: { color: 'text.secondary', fontSize: '.8rem' },
  caseFact: { fontSize: '.75rem', fontWeight: 650, color: 'text.secondary' },
  caseFact2: { mt: 0.75, fontSize: '.875rem' },
  caseLinkSummary: { mt: 1.25, maxWidth: '52ch', fontSize: '.9rem' },
  caseLinkTechnologies: {
    mt: 'auto',
    pt: 3,
    color: 'text.secondary',
    fontSize: '.8rem',
  },
};
