import type { SxProps, Theme } from '@mui/material/styles';

export const boxVariants3: Record<string, SxProps<Theme>> = {
  recommendationEntries: { display: 'grid', gap: 3 },
  resumeEntryGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '1fr auto' },
    columnGap: 3,
    rowGap: 0.25,
  },
  resumeHeader: { textAlign: 'center' },
  resumeHeader2: { mt: 2, '@media print': { display: 'none' } },
  resumeHeader3: {
    display: 'flex',
    justifyContent: 'center',
    flexWrap: 'wrap',
    columnGap: 2,
    rowGap: 0.5,
    mt: 2,
  },
  resumeHeader4: { display: 'contents' },
  resumePdfActions: { display: 'flex', justifyContent: 'center' },
  resumeQualificationSections: { display: 'grid', gap: 1.25 },
  trajectoryEntry: { m: 0, mt: 1, pl: 2.25, color: 'text.secondary' },
  educationEntry: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '1fr auto' },
    columnGap: 3,
    rowGap: 0.25,
  },
  resumeSkill: { color: 'text.primary', fontWeight: 700 },
  referenceLinkItem: {
    '& + &': {
      borderTop: 'var(--site-border-width) solid var(--site-border-subtle)',
    },
  },
  referenceLinkLabel: {
    display: 'grid',
    flex: '1 1 auto',
    minWidth: 0,
    gap: 'var(--site-space-0-5)',
  },
  factEntry: {
    display: 'grid',
    alignContent: 'start',
    gap: 'var(--site-space-1)',
    minWidth: 0,
    padding: 'var(--site-space-3)',
    border: 'var(--site-border-width) solid var(--site-border)',
    borderRadius: 0,
    backgroundColor: 'var(--site-surface)',
  },
  referenceLinkContent: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--site-space-3)',
    minWidth: 0,
    padding: 'var(--site-space-3) var(--site-space-4)',
    color: 'var(--site-text-primary)',
    textDecoration: 'none',
    '&:hover': { backgroundColor: 'var(--site-surface-hover)' },
  },
  factGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))' },
    gap: 'var(--site-space-3)',
    margin: 0,
  },
  linkList: {
    display: 'grid',
    margin: 0,
    padding: 0,
    overflow: 'hidden',
    listStyle: 'none',
    border: 'var(--site-border-width) solid var(--site-border)',
    borderRadius: 0,
    backgroundColor: 'var(--site-surface)',
  },
  linkSectionContent: { display: 'grid', gap: 'var(--site-space-4)' },
  findingSection: {
    display: 'grid',
    gap: 'var(--site-space-4)',
    paddingBlock: 'var(--site-space-6)',
    paddingInline: 0,
    borderRadius: 0,
    backgroundColor: 'var(--site-surface)',
  },
  achadoDetailContent: { display: 'grid', gap: 'var(--site-space-6)' },
  achadoDetailContent2: { display: 'grid', gap: 'var(--site-space-3)' },
  experimentSource: { mt: 6, pt: 4, borderTop: 1, borderColor: 'divider' },
  experimentBody: {
    mt: 6,
    pt: 5,
    borderTop: 1,
    borderColor: 'divider',
    '& p, & li': {
      fontSize: 'var(--site-text-body)',
      lineHeight: 'var(--site-leading-relaxed)',
    },
    '& p': { mb: 3 },
    '& h2': { mt: 5, mb: 2, fontSize: 'var(--site-text-2xl)' },
    '& h3': { mt: 4, mb: 1.5, fontSize: 'var(--site-text-xl)' },
    '& pre': { overflowX: 'auto', p: 2, bgcolor: 'background.paper' },
    '& code': { fontFamily: 'var(--site-font-mono)' },
  },
};
