import type { SxProps, Theme } from '@mui/material/styles';

export const boxVariants1: Record<string, SxProps<Theme>> = {
  brandMonogram: {
    display: 'flex',
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 0.75,
    border: 1,
    borderColor: 'divider',
    bgcolor: 'rgba(234,242,250,.5)',
    color: 'text.secondary',
    fontFamily: 'var(--site-font-logo)',
    fontSize: 'var(--site-text-xs)',
    fontWeight: 500,
    letterSpacing: '-.02em',
    lineHeight: 1,
    userSelect: 'none',
  },
  timelineRow: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '9rem minmax(0, 1fr)' },
    gap: { xs: 1, sm: 4 },
    py: 3,
    borderTop: 1,
    borderColor: 'divider',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    boxSizing: 'border-box',
    py: { xs: 5, md: 6 },
    px: { xs: 3, md: 4 },
    borderTop: 1,
    borderBottom: 1,
    borderColor: 'divider',
    textAlign: 'center',
  },
  emptyState2: {
    m: 0,
    mb: 'var(--site-space-3)',
    color: 'text.secondary',
    fontFamily: 'var(--site-font-mono)',
    fontSize: 'var(--site-text-sm)',
    lineHeight: 'var(--site-leading-tight)',
  },
  sectionHeadingGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'minmax(0, 1fr) auto' },
    columnGap: 3,
    rowGap: 1.25,
    alignItems: 'baseline',
  },
  listingFilterActions: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'stretch',
    gap: 'var(--site-space-2)',
  },
  listingCustomContent: {
    display: 'grid',
    rowGap: 'var(--site-space-5)',
  },
  sectionHeadingContent: {
    position: 'relative',
    mb: { xs: 4, md: 4.5 },
    pb: 3,
    borderBottom: 1,
    borderColor: 'divider',
    '&::before, &::after': {
      position: 'absolute',
      bottom: '-0.25rem',
      width: '1px',
      height: '0.5rem',
      content: '""',
      bgcolor: 'divider',
    },
    '&::before': { left: 0 },
    '&::after': { right: 0 },
  },
  pageTransition: { display: 'flex', flex: 1, flexDirection: 'column', minWidth: 0 },
  siteMainContent: { display: 'flex', flex: 1, flexDirection: 'column', minWidth: 0 },
  siteShell: { color: 'var(--site-text-primary)' },
  siteShell2: {
    position: 'absolute',
    zIndex: 1500,
    left: 8,
    top: -48,
    px: 2,
    py: 1,
    borderRadius: 0,
    border: 1,
    borderColor: 'var(--site-border)',
    bgcolor: 'var(--site-surface)',
    color: 'var(--site-text-primary)',
    textDecoration: 'none',
    transition: 'top .15s ease-out',
    '&:focus-visible': { top: 8 },
  },
};
