import type { SxProps, Theme } from '@mui/material/styles';

export const boxVariants6: Record<string, SxProps<Theme>> = {
  secondaryCaseGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, 1fr)' },
    gap: 2,
    mt: 2,
  },
  referenceCardMeta: { display: 'flex', alignItems: 'center', gap: 1 },
  referenceCardTopics: {
    pt: 'var(--site-space-2)',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 'var(--site-space-1)',
  },
  contentFeedFilters: {
    display: 'flex',
    alignItems: 'stretch',
    gap: 'var(--site-space-2)',
    width: '100%',
    minWidth: 0,
    flex: '1 1 100%',
  },
  contentFeedHeader: {
    maxWidth: 'var(--site-content-max)',
    mb: 'var(--site-space-6)',
    textAlign: 'center',
  },
  feedCard: {
    mt: 'var(--site-space-2)',
    pt: 'var(--site-space-4)',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 'var(--site-space-3)',
    borderTop: 'var(--site-border-width) solid var(--site-border)',
  },
  feedCard2: {
    display: 'flex',
    flex: '1 1 auto',
    flexWrap: 'wrap',
    gap: 'var(--site-space-2)',
  },
  detailArticle: { py: { xs: 8, md: 10 }, maxWidth: '52rem', mx: 'auto' },
  explorationTileGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 'var(--site-space-3)',
    mt: 'var(--site-space-4)',
    '& > *, & [data-exploration-item]': {
      flex: {
        xs: '0 0 calc((100% - var(--site-space-3)) / 2)',
        sm: '0 0 calc((100% - (var(--site-space-3) * 3)) / 4)',
      },
      minWidth: 0,
    },
  },
  connectionsSection: {
    display: 'grid',
    gap: 'var(--site-space-4)',
    padding: 'var(--site-space-6)',
    borderRadius: 0,
    backgroundColor: 'var(--site-surface)',
  },
  connectionsSection2: { display: 'flex', flexDirection: 'column', gap: 'var(--site-space-4)' },
  connectionGroup: { display: 'flex', flexWrap: 'wrap', gap: 'var(--site-space-2)' },
  detailHeader: { maxWidth: '52rem' },
  pageHeader: { maxWidth: '46rem', mb: { xs: 7, md: 9 } },
  sourcePreviewListGroup: { display: 'grid', gap: 'var(--site-space-2)' },
  sourcePreviewListMetadata: { display: 'flex', flexWrap: 'wrap', gap: 'var(--site-space-1)' },
  sourcePreviewListItemFallback: {
    display: 'grid',
    placeItems: 'center',
    height: '100%',
    minHeight: 'var(--site-space-12)',
    color: 'var(--site-primary)',
  },
  sourcePreviewListItemMedia: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'contain',
  },
  technologyMarquee: { mt: 5 },
  technologyMarquee2: { mt: 2, display: 'grid', gap: 1.5 },
  contactProfileGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'minmax(0, 1fr)',
      sm: 'repeat(2, minmax(0, 1fr))',
    },
    gap: 'var(--site-space-3)',
  },
  revealDialogRevealed: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1.5,
    alignItems: 'center',
  },
  revealDialogError: { display: 'flex', flexDirection: 'column', gap: 1.5, alignItems: 'center' },
  revealDialogWorking: { display: 'flex', alignItems: 'center', gap: 1.5 },
};
