import type { SxProps, Theme } from '@mui/material/styles';

const pageLayout: SxProps<Theme> = {
  display: 'flex',
  flex: 1,
  width: '100%',
  maxWidth: 'var(--site-content-max)',
  mx: 'auto',
  minWidth: 0,
  px: 'var(--site-inset-page)',
  boxSizing: 'border-box',
  backgroundColor: 'var(--grid-background)',
  flexDirection: 'column',
  gap: 'var(--site-space-3)',
  pt: 'var(--site-space-2) !important',
  pb: 'var(--site-space-6) !important',
};

export const boxVariants2: Record<string, SxProps<Theme>> = {
  pageLayout,
  aboutPageLayout: pageLayout,
  maintenanceFrame: {
    minHeight: '100svh',
    display: 'grid',
    alignItems: 'center',
    bgcolor: 'background.default',
    color: 'text.primary',
    py: 8,
  },
  profileMilestones: { mt: { xs: 8, md: 10 } },
  aboutStory: { mt: { xs: 8, md: 10 }, maxWidth: '68ch' },
  aboutStory2: { mt: 3, color: 'text.secondary', '& p': { mt: 0, mb: 2 } },
  profileTrajectory: { mt: { xs: 8, md: 10 } },
  profileSummary: { mt: 3, pt: 3, borderTop: 1, borderColor: 'divider' },
  profileSummary2: { color: 'text.secondary', my: 1, pl: 2.5, fontSize: '.875rem' },
  profileSummarySection: { mt: 3, pt: 3, borderTop: 1, borderColor: 'divider' },
  pageSplit: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '7fr 5fr' },
    gap: { xs: 5, md: 8 },
    alignItems: 'start',
  },
  colecaoDetailContent: { mb: { xs: 6, md: 8 }, maxWidth: '60ch' },
  colecaoDetailContent2: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    mb: { xs: 9, md: 11 },
  },
  contactDetails: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '5fr 7fr' },
    gap: { xs: 4, md: 8 },
    alignItems: 'center',
    py: { xs: 6, md: 8 },
    borderTop: 1,
    borderBottom: 1,
    borderColor: 'divider',
  },
  pageSectionStart: { mt: { xs: 6, md: 8 } },
  snippetFile: {
    m: 0,
    p: 2,
    overflow: 'auto',
    fontFamily: 'var(--site-font-mono)',
    fontSize: 'var(--site-text-sm)',
  },
  pageSectionEnd: { mb: { xs: 6, md: 8 } },
  licenseContact: {
    mt: { xs: 4, md: 5 },
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 1,
  },
  statusPage: {
    width: '100%',
    maxWidth: 'var(--site-page-max)',
    mx: 'auto',
    px: 'var(--site-inset-page)',
    boxSizing: 'border-box',
    minHeight: { xs: '55vh', md: '60vh' },
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusContent: { width: '100%', maxWidth: 'var(--site-lede-max)', mx: 'auto' },
  licenseSection: { mt: { xs: 4, md: 5 }, maxWidth: '60ch' },
  resumeSection: { mt: { xs: 4, md: 5 } },
  resumeArticle: {
    '@media print': { maxWidth: 'none', py: 0 },
  },
  resumeBreadcrumbs: {
    display: 'flex',
    justifyContent: 'center',
    '@media print': { display: 'none' },
  },
  resumeCase: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '1fr auto' },
    columnGap: 3,
    rowGap: 0.25,
  },
  resumeWorkSections: { display: 'grid', gap: 3 },
  resumeEntries: { display: 'grid', gap: 2 },
  educationEntries: { display: 'grid', gap: 2 },
  trajectoryEntries: { display: 'grid', gap: 3 },
};
