import type { SxProps, Theme } from '@mui/material/styles';

export const boxVariants5: Record<string, SxProps<Theme>> = {
  mobileSidebarTopbar: {
    display: { xs: 'flex', md: 'none' },
    position: 'sticky',
    top: 0,
    zIndex: 'var(--site-z-nav)',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 'var(--site-topbar-h)',
    px: 2,
    borderBottom: 1,
    borderColor: 'var(--site-border)',
    bgcolor: 'var(--site-surface)',
  },
  stickyRightSidebar: { position: 'sticky', top: 0, height: '100dvh', overflowY: 'auto' },
  sidebarMainColumn: { minWidth: 0, minHeight: '100dvh', display: 'flex', flexDirection: 'column' },
  sidebarContentFooter: {
    display: 'grid',
    minWidth: 0,
    width: '100%',
    maxWidth: 'var(--site-content-max)',
    boxSizing: 'border-box',
    mt: { xs: 'auto', md: 0 },
    mx: 'auto',
    px: 'var(--site-inset-page)',
    py: { xs: 'var(--site-space-8)', md: 'var(--site-space-4)' },
    position: 'relative',
    '&::before': {
      position: 'absolute',
      top: 0,
      right: 'var(--site-inset-page)',
      left: 'var(--site-inset-page)',
      borderTop: 'var(--site-border-width) solid var(--site-border-strong)',
      content: '""',
    },
    color: 'var(--site-text-secondary)',
    overflowX: 'clip',
    gap: 'var(--site-space-6)',
  },
  leftSidebar: { mt: 'var(--site-sidebar-gap)' },
  desktopRightSidebar: {
    display: { xs: 'none', md: 'block' },
    borderLeft: 'var(--site-border-width) solid',
    borderColor: 'var(--site-border-strong)',
  },
  sidebarMainContent: {
    flex: 1,
    minWidth: 0,
    overflowX: 'clip',
    overflowY: 'auto',
    px: { xs: 2, md: 3 },
    scrollbarGutter: 'stable',
    backgroundColor: 'var(--grid-background)',
    backgroundImage:
      'linear-gradient(var(--grid-color) var(--grid-line-width), transparent var(--grid-line-width)), linear-gradient(90deg, var(--grid-color) var(--grid-line-width), transparent var(--grid-line-width))',
    backgroundSize: 'var(--grid-size) var(--grid-size)',
    backgroundPosition: '0 calc(var(--site-space-2) * 9)',
    '@media (min-width: 48rem)': {
      backgroundPosition: 'calc(50% - var(--site-content-half)) calc(var(--site-space-2) * 9)',
    },
  },
  sidebarContentColumn: {
    width: 'min(100%, var(--site-page-max))',
    minHeight: '100%',
    mx: 'auto',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 'var(--site-space-6)',
    backgroundColor: 'var(--grid-background)',
    borderLeft: 'var(--site-border-width) solid var(--site-border)',
    borderRight: 'var(--site-border-width) solid var(--site-border)',
  },
  rightSidebar: { p: 3, minWidth: 0 },
  featuredCaseFacts: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(3, 1fr)' },
    gap: 2.5,
    mt: 3,
    pt: 3,
    borderTop: 1,
    borderColor: 'divider',
  },
  featuredCaseDetails: { p: { xs: 3, md: 4 }, display: 'flex', flexDirection: 'column' },
  featuredCaseFooter: {
    mt: 'auto',
    pt: 3,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 2,
    flexWrap: 'wrap',
  },
  featuredCaseVisual: {
    p: { xs: 2, sm: 3 },
    display: 'grid',
    alignItems: 'center',
    bgcolor: '#eef2f8',
    borderRight: { md: 1 },
    borderBottom: { xs: 1, md: 0 },
    borderColor: 'divider',
  },
};
