import type { SxProps, Theme } from '@mui/material/styles';

export const boxVariants8: Record<string, SxProps<Theme>> = {
  sourcePreviewSurfaceFeed: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '1fr 2fr' },
    minWidth: 0,
    overflow: 'hidden',
    border: 'var(--site-border-width) solid var(--site-border)',
    borderColor: 'var(--site-border)',
    backgroundColor: 'var(--site-surface-muted)',
  },
  sourcePreviewSurfaceDetail: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'minmax(0, 2fr) minmax(0, 3fr)' },
    minWidth: 0,
    overflow: 'hidden',
    border: 'var(--site-border-width) solid var(--site-border)',
    borderColor: 'var(--site-border-strong)',
    backgroundColor: 'var(--site-surface)',
  },
  sourcePreviewSurfaceTable: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '1fr 2fr' },
    minWidth: 0,
    overflow: 'hidden',
    border: 'var(--site-border-width) solid var(--site-border)',
    borderColor: 'var(--site-border)',
    backgroundColor: 'var(--site-surface-muted)',
  },
  sourcePreviewMediaFeed: {
    display: 'grid',
    placeItems: 'center',
    height: '100%',
    minHeight: { xs: 'var(--site-space-12)', sm: 'var(--site-tile-min-h)' },
    overflow: 'hidden',
    backgroundColor: 'var(--site-accent-bg)',
  },
  sourcePreviewMediaDetail: {
    display: 'grid',
    placeItems: 'center',
    height: '100%',
    minHeight: { xs: 'var(--site-space-12)', sm: '100%' },
    overflow: 'hidden',
    backgroundColor: 'var(--site-accent-bg)',
  },
  sourcePreviewMediaTable: {
    display: 'grid',
    placeItems: 'center',
    height: '100%',
    minHeight: { xs: 'var(--site-space-12)', sm: 'var(--site-tile-min-h)' },
    overflow: 'hidden',
    backgroundColor: 'var(--site-accent-bg)',
  },
  technologyChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'var(--site-space-1)',
    minWidth: 0,
    padding: 'var(--site-space-1) var(--site-space-2)',
    border: 'var(--site-border-width) solid var(--site-border)',
    color: 'var(--site-text-secondary)',
    fontSize: 'var(--site-text-xs)',
    whiteSpace: 'nowrap',
  },
  technologyMarquee3: {
    overflow: 'hidden',
    maskImage: 'linear-gradient(to right, transparent, #000 6%, #000 94%, transparent)',
    WebkitMaskImage: 'linear-gradient(to right, transparent, #000 6%, #000 94%, transparent)',
  },
  technologyMarqueeTrack: {
    display: 'flex',
    width: 'max-content',
    gap: 1.5,
    animationName: 'technology-marquee-scroll',
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
    '@keyframes technology-marquee-scroll': {
      from: { transform: 'translate3d(0, 0, 0)' },
      to: { transform: 'translate3d(-50%, 0, 0)' },
    },
  },
  technologyMarqueeList: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
    m: 0,
    p: 0,
    listStyle: 'none',
    flex: '0 0 auto',
  },
  caseIllustrationCompact: {
    position: 'relative',
    isolation: 'isolate',
    overflow: 'hidden',
    borderRadius: 0,
    p: { xs: 1.5, md: 2 },
    aspectRatio: '16 / 9',
  },
  caseIllustrationFull: {
    position: 'relative',
    isolation: 'isolate',
    overflow: 'hidden',
    borderRadius: 0,
    p: { xs: 2, md: 4 },
    aspectRatio: '4 / 3',
  },
  protectedEmailDialogIcon: { display: 'inline-flex' },
};
