import type { SxProps, Theme } from '@mui/material/styles';
import { richTextBody } from './rich-text-body';

export const boxVariants4: Record<string, SxProps<Theme>> = {
  projectRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--site-space-2)',
    p: 'var(--site-inset-card)',
    borderLeft: 'var(--site-feed-accent-w) solid var(--site-primary)',
    borderTop: 'var(--site-border-width) solid var(--site-border)',
    borderRight: 'var(--site-border-width) solid var(--site-border)',
    borderBottom: 'var(--site-border-width) solid var(--site-border)',
    backgroundColor: 'var(--site-surface)',
    '&:hover .project-row-title': { color: 'var(--site-primary)' },
  },
  writingBody: {
    mt: 7,
    pt: 5,
    borderTop: 1,
    borderColor: 'divider',
    '& p, & li': { fontSize: '1.1rem', lineHeight: 1.8 },
    '& p': { mb: 3 },
    '& h2': { fontSize: '1.75rem', mt: 6, mb: 2 },
    '& h3': { fontSize: '1.35rem', mt: 5, mb: 2 },
    '& ul, & ol': { pl: 3, mb: 3 },
    '& pre': { overflowX: 'auto', p: 2.5, bgcolor: 'background.paper' },
    '& code': { fontFamily: 'var(--font-mono)' },
    '& a': { color: 'primary.main' },
  },
  topicItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 'var(--site-space-3)',
    p: 'var(--site-inset-card)',
    border: 'var(--site-border-width) solid var(--site-border)',
    borderLeft: 'var(--site-feed-accent-w) solid var(--site-primary)',
    backgroundColor: 'var(--site-surface)',
  },
  caseDetailContent: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' },
    gap: 3,
    mt: { xs: 6, md: 8 },
  },
  caseDetailContent2: richTextBody,
  projectDetailContent: { mt: 6, pt: 4, borderTop: 1, borderColor: 'divider' },
  projectDetailContent2: richTextBody,
  projectOverview: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)' },
    gap: 3,
    mt: 6,
    pt: 4,
    borderTop: 1,
    borderColor: 'divider',
  },
  stickyLeftSidebar: { position: 'sticky', top: 0, height: '100dvh', overflowY: 'auto' },
  sidebarBrandRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    minHeight: '2rem',
  },
  desktopLeftSidebar: {
    display: { xs: 'none', md: 'block' },
    borderRight: 'var(--site-border-width) solid',
    borderColor: 'var(--site-border-strong)',
  },
};
