export const homeGalleryFeedSectionTemplates = [
  {
    id: 'recent-writing',
    titleKey: 'recentWriting',
    actionKey: 'viewWriting',
    href: '/writing',
    source: 'recent',
    kind: 'writing',
    mode: 'grid',
  },
  {
    id: 'recent-findings',
    titleKey: 'recentFindings',
    actionKey: 'viewFindings',
    href: '/findings',
    source: 'recent',
    kind: 'finding',
    mode: 'list',
  },
  {
    id: 'recent-collections',
    titleKey: 'recentCollections',
    actionKey: 'viewCollections',
    href: '/collections',
    source: 'recent',
    kind: 'collection',
    mode: 'grid',
  },
  {
    id: 'popular-writing',
    titleKey: 'popularWriting',
    actionKey: 'viewWriting',
    href: '/writing',
    source: 'popular',
    kind: 'writing',
    mode: 'grid',
  },
  {
    id: 'popular-findings',
    titleKey: 'popularFindings',
    actionKey: 'viewPopular',
    href: '/findings?sort=popular',
    source: 'popular',
    kind: 'finding',
    mode: 'list',
  },
  {
    id: 'popular-collections',
    titleKey: 'popularCollections',
    actionKey: 'viewCollections',
    href: '/collections',
    source: 'popular',
    kind: 'collection',
    mode: 'grid',
  },
] as const;
