/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as HealthRouteImport } from './routes/health'
import { Route as SiteSupportRouteImport } from './routes/site-support'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteSplatRouteImport } from './routes/_site/$'
import { Route as SiteSplatSupportRouteImport } from './routes/_site/splat-support'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSupportRoute = SiteSupportRouteImport.update({
  id: '/site-support',
  path: '/site-support',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSplatRoute = SiteSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSplatSupportRoute = SiteSplatSupportRouteImport.update({
  id: '/splat-support',
  path: '/splat-support',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/health': typeof HealthRoute
  '/site-support': typeof SiteSupportRoute
  '/$': typeof SiteSplatRoute
  '/splat-support': typeof SiteSplatSupportRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/site-support': typeof SiteSupportRoute
  '/$': typeof SiteSplatRoute
  '/splat-support': typeof SiteSplatSupportRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/health': typeof HealthRoute
  '/site-support': typeof SiteSupportRoute
  '/_site/$': typeof SiteSplatRoute
  '/_site/splat-support': typeof SiteSplatSupportRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/health' | '/site-support' | '/$' | '/splat-support'
  fileRoutesByTo: FileRoutesByTo
  to: '/health' | '/site-support' | '/$' | '/splat-support' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/health'
    | '/site-support'
    | '/_site/$'
    | '/_site/splat-support'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  HealthRoute: typeof HealthRoute
  SiteSupportRoute: typeof SiteSupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-support': {
      id: '/site-support'
      path: '/site-support'
      fullPath: '/site-support'
      preLoaderRoute: typeof SiteSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/$': {
      id: '/_site/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SiteSplatRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/splat-support': {
      id: '/_site/splat-support'
      path: '/splat-support'
      fullPath: '/splat-support'
      preLoaderRoute: typeof SiteSplatSupportRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteSplatRoute: typeof SiteSplatRoute
  SiteSplatSupportRoute: typeof SiteSplatSupportRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteSplatRoute: SiteSplatRoute,
  SiteSplatSupportRoute: SiteSplatSupportRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  HealthRoute: HealthRoute,
  SiteSupportRoute: SiteSupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
