apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog
resources:
  - namespace.yaml
  - app/deployment.yaml
  - app/service.yaml
  - app/configmap.yaml
  - postgres/cluster.yaml
  - cloudflared/deployment.yaml
  - cloudflared/configmap.yaml
