$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  language: typescript

tasks:
  typecheck:
    command: 'tsc --noEmit'
    inputs:
      - '**/*.{ts,tsx,mts,cts}'
      - 'tsconfig*.json'
      - '/tsconfig*.json'
      - '/.config/moon/**/*.yml'
    tags:
      - check
      - typecheck

