name: portfolio-coder

services:
  app:
    extends:
      file: ../compose.yaml
      service: app
    ports:
      - "3000:3000"
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:9000:9000"
    stdin_open: true
    tty: true
